import { LucideIcon } from 'lucide-react';

// Production domain used for share links, QR codes, and handle URLs
export const SITE_DOMAIN = 'https://medicalbaise.com';
import {
  Heart,
  Baby,
  Sparkles,
  Bone,
  User,
  Stethoscope,
  Brain,
  Smile,
  Eye,
  BrainCircuit,
  Ear,
  Syringe,
  Activity,
  Microscope,
  Pill,
  Video,
  Clock,
  Shield,
  Apple,
  MessageCircle,
  Wind,
  Droplets,
  Flame,
  Scissors,
  Radiation,
  Dna,
  Scan,
  HeartPulse,
  Thermometer,
  HandHeart,
  Footprints,
  PersonStanding,
  Ribbon,
  BedDouble,
  Ambulance,
  Cross,
  Flower2,
  TreePine,
  Waves,
  Zap,
  CircleDot,
  ShieldCheck,
  Gauge,
  Hand,
  Loader,
  Landmark,
  Blend,
  Search,
  FileHeart,
  Contact,
} from 'lucide-react';

export interface MedicalCategory {
  id: string;
  name_en: string;
  name_pt: string;
  icon: LucideIcon;
  color: string;
  description_en: string;
  description_pt: string;
}

export const MEDICAL_CATEGORIES: MedicalCategory[] = [
  {
    id: 'general-practice',
    name_en: 'General Practice',
    name_pt: 'Clínica Geral',
    icon: Stethoscope,
    color: '#06B6D4',
    description_en: 'Primary care and general medical consultation',
    description_pt: 'Atendimento primário e consulta médica geral',
  },
  {
    id: 'cardiology',
    name_en: 'Cardiology',
    name_pt: 'Cardiologia',
    icon: Heart,
    color: '#EF4444',
    description_en: 'Heart and cardiovascular care',
    description_pt: 'Cuidados cardíacos e cardiovasculares',
  },
  {
    id: 'dermatology',
    name_en: 'Dermatology',
    name_pt: 'Dermatologia',
    icon: Sparkles,
    color: '#8B5CF6',
    description_en: 'Skin, hair, and nail care',
    description_pt: 'Cuidados com pele, cabelo e unhas',
  },
  {
    id: 'pediatrics',
    name_en: 'Pediatrics',
    name_pt: 'Pediatria',
    icon: Baby,
    color: '#F59E0B',
    description_en: 'Children and adolescent care',
    description_pt: 'Cuidados infantis e adolescentes',
  },
  {
    id: 'dentistry',
    name_en: 'Dentistry',
    name_pt: 'Odontologia',
    icon: Smile,
    color: '#14B8A6',
    description_en: 'Dental and oral health',
    description_pt: 'Saúde dental e bucal',
  },
  {
    id: 'orthopedics',
    name_en: 'Orthopedics',
    name_pt: 'Ortopedia',
    icon: Bone,
    color: '#10B981',
    description_en: 'Bone, joint, and muscle care',
    description_pt: 'Cuidados com ossos, articulações e músculos',
  },
  {
    id: 'gynecology',
    name_en: 'Gynecology & Obstetrics',
    name_pt: 'Ginecologia e Obstetrícia',
    icon: User,
    color: '#EC4899',
    description_en: "Women's health, pregnancy, and childbirth",
    description_pt: 'Saúde da mulher, gravidez e parto',
  },
  {
    id: 'psychiatry',
    name_en: 'Psychiatry',
    name_pt: 'Psiquiatria',
    icon: Brain,
    color: '#6366F1',
    description_en: 'Mental health and behavioral care',
    description_pt: 'Saúde mental e cuidados comportamentais',
  },
  {
    id: 'ophthalmology',
    name_en: 'Ophthalmology',
    name_pt: 'Oftalmologia',
    icon: Eye,
    color: '#3B82F6',
    description_en: 'Eye care and vision',
    description_pt: 'Cuidados com os olhos e visão',
  },
  {
    id: 'neurology',
    name_en: 'Neurology',
    name_pt: 'Neurologia',
    icon: BrainCircuit,
    color: '#7C3AED',
    description_en: 'Brain and nervous system',
    description_pt: 'Cérebro e sistema nervoso',
  },
  {
    id: 'ent',
    name_en: 'ENT (Ear, Nose, Throat)',
    name_pt: 'Otorrinolaringologia',
    icon: Ear,
    color: '#F97316',
    description_en: 'Ear, nose, and throat care',
    description_pt: 'Cuidados com ouvido, nariz e garganta',
  },
  {
    id: 'endocrinology',
    name_en: 'Endocrinology',
    name_pt: 'Endocrinologia',
    icon: Activity,
    color: '#84CC16',
    description_en: 'Hormone and metabolic disorders',
    description_pt: 'Distúrbios hormonais e metabólicos',
  },
  {
    id: 'gastroenterology',
    name_en: 'Gastroenterology',
    name_pt: 'Gastroenterologia',
    icon: Microscope,
    color: '#0EA5E9',
    description_en: 'Digestive system care',
    description_pt: 'Cuidados do sistema digestivo',
  },
  {
    id: 'urology',
    name_en: 'Urology',
    name_pt: 'Urologia',
    icon: Syringe,
    color: '#A855F7',
    description_en: 'Urinary tract and male reproductive health',
    description_pt: 'Saúde do trato urinário e reprodutivo masculino',
  },
  {
    id: 'oncology',
    name_en: 'Oncology',
    name_pt: 'Oncologia',
    icon: Ribbon,
    color: '#DC2626',
    description_en: 'Cancer diagnosis and treatment',
    description_pt: 'Diagnóstico e tratamento de câncer',
  },
  {
    id: 'therapy',
    name_en: 'Therapy / Psychology',
    name_pt: 'Terapia / Psicologia',
    icon: Brain,
    color: '#8B5CF6',
    description_en: 'Mental health therapy and counseling',
    description_pt: 'Terapia e aconselhamento de saúde mental',
  },
  {
    id: 'dietitian',
    name_en: 'Dietitian / Nutritionist',
    name_pt: 'Nutricionista',
    icon: Apple,
    color: '#22C55E',
    description_en: 'Nutrition and dietary planning',
    description_pt: 'Nutrição e planejamento alimentar',
  },
  {
    id: 'speech-pathology',
    name_en: 'Speech & Language Pathology',
    name_pt: 'Fonoaudiologia',
    icon: MessageCircle,
    color: '#F472B6',
    description_en: 'Speech, language, and swallowing disorders',
    description_pt: 'Distúrbios de fala, linguagem e deglutição',
  },
  {
    id: 'doula',
    name_en: 'Doula',
    name_pt: 'Doula',
    icon: HandHeart,
    color: '#E879A8',
    description_en: 'Birth support, prenatal and postpartum care',
    description_pt: 'Apoio ao parto, cuidados pré e pós-natal',
  },
  // ──────────────────────────────────────────
  // SURGICAL SPECIALTIES
  // ──────────────────────────────────────────
  {
    id: 'general-surgery',
    name_en: 'General Surgery',
    name_pt: 'Cirurgia Geral',
    icon: Scissors,
    color: '#B91C1C',
    description_en: 'Surgical procedures and operative care',
    description_pt: 'Procedimentos cirúrgicos e cuidados operatórios',
  },
  {
    id: 'neurosurgery',
    name_en: 'Neurosurgery',
    name_pt: 'Neurocirurgia',
    icon: BrainCircuit,
    color: '#4C1D95',
    description_en: 'Brain and spinal cord surgery',
    description_pt: 'Cirurgia do cérebro e medula espinhal',
  },
  {
    id: 'cardiac-surgery',
    name_en: 'Cardiac Surgery',
    name_pt: 'Cirurgia Cardíaca',
    icon: HeartPulse,
    color: '#991B1B',
    description_en: 'Heart and cardiovascular surgery',
    description_pt: 'Cirurgia cardíaca e cardiovascular',
  },
  {
    id: 'plastic-surgery',
    name_en: 'Plastic & Reconstructive Surgery',
    name_pt: 'Cirurgia Plástica e Reconstrutiva',
    icon: Sparkles,
    color: '#DB2777',
    description_en: 'Cosmetic and reconstructive surgical procedures',
    description_pt: 'Procedimentos cirúrgicos cosméticos e reconstrutivos',
  },
  {
    id: 'vascular-surgery',
    name_en: 'Vascular Surgery',
    name_pt: 'Cirurgia Vascular',
    icon: Activity,
    color: '#9F1239',
    description_en: 'Blood vessel and circulatory system surgery',
    description_pt: 'Cirurgia de vasos sanguíneos e sistema circulatório',
  },
  {
    id: 'thoracic-surgery',
    name_en: 'Thoracic Surgery',
    name_pt: 'Cirurgia Torácica',
    icon: Wind,
    color: '#7F1D1D',
    description_en: 'Chest, lung, and esophageal surgery',
    description_pt: 'Cirurgia de tórax, pulmão e esôfago',
  },
  {
    id: 'colorectal-surgery',
    name_en: 'Colorectal Surgery',
    name_pt: 'Cirurgia Colorretal',
    icon: Scissors,
    color: '#78350F',
    description_en: 'Colon, rectum, and anal surgery',
    description_pt: 'Cirurgia de cólon, reto e anal',
  },
  // ──────────────────────────────────────────
  // ON-CALL / EMERGENCY / CRITICAL CARE
  // ──────────────────────────────────────────
  {
    id: 'emergency-medicine',
    name_en: 'Emergency Medicine',
    name_pt: 'Medicina de Emergência',
    icon: Ambulance,
    color: '#DC2626',
    description_en: 'Acute emergency and trauma care',
    description_pt: 'Cuidados de emergência e trauma agudo',
  },
  {
    id: 'intensivist',
    name_en: 'Intensivist (ICU)',
    name_pt: 'Intensivista (UTI)',
    icon: HeartPulse,
    color: '#B91C1C',
    description_en: 'Intensive care unit critical care',
    description_pt: 'Cuidados intensivos em UTI',
  },
  {
    id: 'hospitalist',
    name_en: 'Hospitalist',
    name_pt: 'Hospitalista',
    icon: BedDouble,
    color: '#1D4ED8',
    description_en: 'Inpatient hospital-based medicine',
    description_pt: 'Medicina hospitalar para pacientes internados',
  },
  {
    id: 'trauma-surgery',
    name_en: 'Trauma Surgery',
    name_pt: 'Cirurgia de Trauma',
    icon: Zap,
    color: '#EA580C',
    description_en: 'Emergency surgical care for traumatic injuries',
    description_pt: 'Cuidados cirúrgicos de emergência para lesões traumáticas',
  },
  {
    id: 'neonatology',
    name_en: 'Neonatology',
    name_pt: 'Neonatologia',
    icon: Baby,
    color: '#F59E0B',
    description_en: 'Newborn intensive and critical care',
    description_pt: 'Cuidados intensivos e críticos neonatais',
  },
  // ──────────────────────────────────────────
  // INTERNAL MEDICINE SUBSPECIALTIES
  // ──────────────────────────────────────────
  {
    id: 'pulmonology',
    name_en: 'Pulmonology',
    name_pt: 'Pneumologia',
    icon: Wind,
    color: '#0284C7',
    description_en: 'Lung and respiratory system care',
    description_pt: 'Cuidados pulmonares e do sistema respiratório',
  },
  {
    id: 'nephrology',
    name_en: 'Nephrology',
    name_pt: 'Nefrologia',
    icon: Droplets,
    color: '#0891B2',
    description_en: 'Kidney disease and renal care',
    description_pt: 'Doenças renais e cuidados nefróticos',
  },
  {
    id: 'rheumatology',
    name_en: 'Rheumatology',
    name_pt: 'Reumatologia',
    icon: Bone,
    color: '#D97706',
    description_en: 'Autoimmune and musculoskeletal disorders',
    description_pt: 'Distúrbios autoimunes e musculoesqueléticos',
  },
  {
    id: 'hematology',
    name_en: 'Hematology',
    name_pt: 'Hematologia',
    icon: Droplets,
    color: '#BE123C',
    description_en: 'Blood disorders and transfusion medicine',
    description_pt: 'Distúrbios do sangue e medicina transfusional',
  },
  {
    id: 'infectious-disease',
    name_en: 'Infectious Disease',
    name_pt: 'Infectologia',
    icon: ShieldCheck,
    color: '#059669',
    description_en: 'Bacterial, viral, and parasitic infections',
    description_pt: 'Infecções bacterianas, virais e parasitárias',
  },
  {
    id: 'allergy-immunology',
    name_en: 'Allergy & Immunology',
    name_pt: 'Alergia e Imunologia',
    icon: Flower2,
    color: '#65A30D',
    description_en: 'Allergies, asthma, and immune system disorders',
    description_pt: 'Alergias, asma e distúrbios do sistema imunológico',
  },
  {
    id: 'geriatrics',
    name_en: 'Geriatrics',
    name_pt: 'Geriatria',
    icon: PersonStanding,
    color: '#78716C',
    description_en: 'Elderly and aging population care',
    description_pt: 'Cuidados com idosos e população em envelhecimento',
  },
  // ──────────────────────────────────────────
  // DIAGNOSTIC & IMAGING
  // ──────────────────────────────────────────
  {
    id: 'radiology',
    name_en: 'Radiology',
    name_pt: 'Radiologia',
    icon: Scan,
    color: '#475569',
    description_en: 'Medical imaging and diagnostic radiology',
    description_pt: 'Imagem médica e radiologia diagnóstica',
  },
  {
    id: 'pathology',
    name_en: 'Pathology',
    name_pt: 'Patologia',
    icon: Microscope,
    color: '#6B21A8',
    description_en: 'Laboratory diagnostics and tissue analysis',
    description_pt: 'Diagnósticos laboratoriais e análise de tecidos',
  },
  {
    id: 'nuclear-medicine',
    name_en: 'Nuclear Medicine',
    name_pt: 'Medicina Nuclear',
    icon: Radiation,
    color: '#4338CA',
    description_en: 'Radioactive diagnostics and therapy',
    description_pt: 'Diagnósticos e terapia radioativos',
  },
  {
    id: 'genetics',
    name_en: 'Medical Genetics',
    name_pt: 'Genética Médica',
    icon: Dna,
    color: '#7E22CE',
    description_en: 'Genetic testing, counseling, and hereditary conditions',
    description_pt: 'Testes genéticos, aconselhamento e condições hereditárias',
  },
  // ──────────────────────────────────────────
  // ANESTHESIA & PAIN MANAGEMENT
  // ──────────────────────────────────────────
  {
    id: 'anesthesiology',
    name_en: 'Anesthesiology',
    name_pt: 'Anestesiologia',
    icon: Gauge,
    color: '#334155',
    description_en: 'Anesthesia for surgical and procedural care',
    description_pt: 'Anestesia para cuidados cirúrgicos e procedimentais',
  },
  {
    id: 'pain-management',
    name_en: 'Pain Management',
    name_pt: 'Medicina da Dor',
    icon: Flame,
    color: '#C2410C',
    description_en: 'Chronic and acute pain treatment',
    description_pt: 'Tratamento de dor crônica e aguda',
  },
  // ──────────────────────────────────────────
  // REHABILITATION & ALLIED HEALTH
  // ──────────────────────────────────────────
  {
    id: 'physical-therapy',
    name_en: 'Physical Therapy / Physiotherapy',
    name_pt: 'Fisioterapia',
    icon: PersonStanding,
    color: '#0D9488',
    description_en: 'Movement rehabilitation and physical recovery',
    description_pt: 'Reabilitação de movimentos e recuperação física',
  },
  {
    id: 'occupational-therapy',
    name_en: 'Occupational Therapy',
    name_pt: 'Terapia Ocupacional',
    icon: Hand,
    color: '#0E7490',
    description_en: 'Daily living skills and functional rehabilitation',
    description_pt: 'Habilidades para vida diária e reabilitação funcional',
  },
  {
    id: 'physiatry',
    name_en: 'Physical Medicine & Rehabilitation',
    name_pt: 'Fisiatria',
    icon: Loader,
    color: '#0F766E',
    description_en: 'Non-surgical musculoskeletal and neurological rehab',
    description_pt: 'Reabilitação musculoesquelética e neurológica não cirúrgica',
  },
  {
    id: 'respiratory-therapy',
    name_en: 'Respiratory Therapy',
    name_pt: 'Terapia Respiratória',
    icon: Wind,
    color: '#0369A1',
    description_en: 'Respiratory care and ventilator management',
    description_pt: 'Cuidados respiratórios e gerenciamento de ventiladores',
  },
  // ──────────────────────────────────────────
  // SPECIALTY & NICHE
  // ──────────────────────────────────────────
  {
    id: 'sports-medicine',
    name_en: 'Sports Medicine',
    name_pt: 'Medicina Esportiva',
    icon: Footprints,
    color: '#16A34A',
    description_en: 'Athletic injuries and performance medicine',
    description_pt: 'Lesões esportivas e medicina de desempenho',
  },
  {
    id: 'palliative-care',
    name_en: 'Palliative Care & Hospice',
    name_pt: 'Cuidados Paliativos',
    icon: HandHeart,
    color: '#A16207',
    description_en: 'End-of-life and comfort-focused care',
    description_pt: 'Cuidados de fim de vida e conforto',
  },
  {
    id: 'sleep-medicine',
    name_en: 'Sleep Medicine',
    name_pt: 'Medicina do Sono',
    icon: BedDouble,
    color: '#1E3A5F',
    description_en: 'Sleep disorders diagnosis and treatment',
    description_pt: 'Diagnóstico e tratamento de distúrbios do sono',
  },
  {
    id: 'wound-care',
    name_en: 'Wound Care',
    name_pt: 'Tratamento de Feridas',
    icon: Cross,
    color: '#B45309',
    description_en: 'Chronic wound management and healing',
    description_pt: 'Gestão e cicatrização de feridas crônicas',
  },
  {
    id: 'toxicology',
    name_en: 'Toxicology',
    name_pt: 'Toxicologia',
    icon: Thermometer,
    color: '#92400E',
    description_en: 'Poisoning, overdose, and toxic exposure treatment',
    description_pt: 'Tratamento de envenenamento, overdose e exposição tóxica',
  },
  {
    id: 'addiction-medicine',
    name_en: 'Addiction Medicine',
    name_pt: 'Medicina de Dependência',
    icon: ShieldCheck,
    color: '#4A044E',
    description_en: 'Substance use disorders and recovery',
    description_pt: 'Distúrbios por uso de substâncias e recuperação',
  },
  // ──────────────────────────────────────────
  // DENTAL SPECIALTIES
  // ──────────────────────────────────────────
  {
    id: 'orthodontics',
    name_en: 'Orthodontics',
    name_pt: 'Ortodontia',
    icon: Smile,
    color: '#2563EB',
    description_en: 'Teeth alignment and bite correction',
    description_pt: 'Alinhamento dentário e correção de mordida',
  },
  {
    id: 'oral-surgery',
    name_en: 'Oral & Maxillofacial Surgery',
    name_pt: 'Cirurgia Bucomaxilofacial',
    icon: Scissors,
    color: '#1E40AF',
    description_en: 'Surgical procedures of mouth, jaw, and face',
    description_pt: 'Procedimentos cirúrgicos de boca, mandíbula e face',
  },
  {
    id: 'periodontics',
    name_en: 'Periodontics',
    name_pt: 'Periodontia',
    icon: Smile,
    color: '#047857',
    description_en: 'Gum disease treatment and dental implants',
    description_pt: 'Tratamento de doenças gengivais e implantes dentários',
  },
  {
    id: 'endodontics',
    name_en: 'Endodontics',
    name_pt: 'Endodontia',
    icon: CircleDot,
    color: '#0F766E',
    description_en: 'Root canal therapy and dental pulp treatment',
    description_pt: 'Tratamento de canal radicular e polpa dentária',
  },
  // ──────────────────────────────────────────
  // NURSING & CLINICAL SUPPORT
  // ──────────────────────────────────────────
  {
    id: 'nurse-practitioner',
    name_en: 'Nurse Practitioner (NP)',
    name_pt: 'Enfermeiro(a) Especialista',
    icon: Cross,
    color: '#0891B2',
    description_en: 'Advanced practice nursing and primary care',
    description_pt: 'Enfermagem de prática avançada e atenção primária',
  },
  {
    id: 'registered-nurse',
    name_en: 'Registered Nurse (RN)',
    name_pt: 'Enfermeiro(a) Registrado(a)',
    icon: Cross,
    color: '#06B6D4',
    description_en: 'Professional nursing care and patient management',
    description_pt: 'Cuidados profissionais de enfermagem e gerenciamento de pacientes',
  },
  {
    id: 'certified-nursing-assistant',
    name_en: 'Certified Nursing Assistant (CNA)',
    name_pt: 'Auxiliar de Enfermagem',
    icon: HandHeart,
    color: '#67E8F9',
    description_en: 'Basic patient care and nursing support',
    description_pt: 'Cuidados básicos com pacientes e suporte de enfermagem',
  },
  {
    id: 'midwifery',
    name_en: 'Midwifery',
    name_pt: 'Obstetrícia / Parteira',
    icon: Baby,
    color: '#F472B6',
    description_en: 'Pregnancy, labor, and postpartum midwifery care',
    description_pt: 'Cuidados de obstetrícia na gravidez, parto e pós-parto',
  },
  // ──────────────────────────────────────────
  // LABORATORY & DIAGNOSTICS
  // ──────────────────────────────────────────
  {
    id: 'medical-lab-tech',
    name_en: 'Medical Lab Technologist',
    name_pt: 'Técnico(a) de Laboratório',
    icon: Microscope,
    color: '#7C3AED',
    description_en: 'Clinical laboratory testing and analysis',
    description_pt: 'Testes e análises laboratoriais clínicas',
  },
  {
    id: 'phlebotomy',
    name_en: 'Phlebotomy',
    name_pt: 'Flebotomia',
    icon: Syringe,
    color: '#BE185D',
    description_en: 'Blood collection and venipuncture services',
    description_pt: 'Coleta de sangue e serviços de punção venosa',
  },
  {
    id: 'radiologic-tech',
    name_en: 'Radiologic Technologist',
    name_pt: 'Técnico(a) em Radiologia',
    icon: Scan,
    color: '#64748B',
    description_en: 'X-ray, CT, and MRI imaging services',
    description_pt: 'Serviços de imagem por raio-X, tomografia e ressonância',
  },
  // ──────────────────────────────────────────
  // ALTERNATIVE & COMPLEMENTARY
  // ──────────────────────────────────────────
  {
    id: 'chiropractic',
    name_en: 'Chiropractic',
    name_pt: 'Quiropraxia',
    icon: PersonStanding,
    color: '#4D7C0F',
    description_en: 'Spinal alignment and musculoskeletal manipulation',
    description_pt: 'Alinhamento espinhal e manipulação musculoesquelética',
  },
  {
    id: 'acupuncture',
    name_en: 'Acupuncture',
    name_pt: 'Acupuntura',
    icon: CircleDot,
    color: '#B45309',
    description_en: 'Traditional and medical acupuncture therapy',
    description_pt: 'Terapia de acupuntura tradicional e médica',
  },
  {
    id: 'naturopathy',
    name_en: 'Naturopathic Medicine',
    name_pt: 'Naturopatia',
    icon: TreePine,
    color: '#15803D',
    description_en: 'Natural and holistic health approaches',
    description_pt: 'Abordagens de saúde natural e holística',
  },
  // ──────────────────────────────────────────
  // OPTOMETRY & AUDIOLOGY
  // ──────────────────────────────────────────
  {
    id: 'optometry',
    name_en: 'Optometry',
    name_pt: 'Optometria',
    icon: Eye,
    color: '#2563EB',
    description_en: 'Vision testing, eyeglasses, and contact lens fitting',
    description_pt: 'Teste de visão, óculos e adaptação de lentes de contato',
  },
  {
    id: 'audiology',
    name_en: 'Audiology',
    name_pt: 'Audiologia',
    icon: Ear,
    color: '#EA580C',
    description_en: 'Hearing evaluation and hearing aid fitting',
    description_pt: 'Avaliação auditiva e adaptação de aparelhos auditivos',
  },
  // ──────────────────────────────────────────
  // HOME HEALTH & SPECIALIZED ON-CALL
  // ──────────────────────────────────────────
  {
    id: 'home-health',
    name_en: 'Home Health Services',
    name_pt: 'Atendimento Domiciliar',
    icon: Landmark,
    color: '#0D9488',
    description_en: 'In-home medical care and health monitoring',
    description_pt: 'Cuidados médicos domiciliares e monitoramento de saúde',
  },
  {
    id: 'telehealth',
    name_en: 'Telehealth / Telemedicine',
    name_pt: 'Telemedicina',
    icon: Video,
    color: '#2563EB',
    description_en: 'Remote virtual medical consultations',
    description_pt: 'Consultas médicas virtuais remotas',
  },
  {
    id: 'paramedic',
    name_en: 'Paramedic / EMT',
    name_pt: 'Paramédico / Socorrista',
    icon: Ambulance,
    color: '#E11D48',
    description_en: 'Pre-hospital emergency medical care',
    description_pt: 'Cuidados médicos de emergência pré-hospitalares',
  },
  // ──────────────────────────────────────────
  // PHARMACY & CLINICAL PHARMACOLOGY
  // ──────────────────────────────────────────
  {
    id: 'pharmacy',
    name_en: 'Pharmacy / Clinical Pharmacist',
    name_pt: 'Farmácia / Farmacêutico Clínico',
    icon: Pill,
    color: '#16A34A',
    description_en: 'Medication management and pharmaceutical care',
    description_pt: 'Gerenciamento de medicamentos e cuidados farmacêuticos',
  },
  // ──────────────────────────────────────────
  // SOCIAL WORK & PATIENT ADVOCACY
  // ──────────────────────────────────────────
  {
    id: 'medical-social-work',
    name_en: 'Medical Social Work',
    name_pt: 'Serviço Social Médico',
    icon: FileHeart,
    color: '#7C3AED',
    description_en: 'Patient advocacy, discharge planning, and support',
    description_pt: 'Advocacia do paciente, planejamento de alta e suporte',
  },
  {
    id: 'patient-advocacy',
    name_en: 'Patient Advocate / Navigator',
    name_pt: 'Navegador de Pacientes',
    icon: Contact,
    color: '#0891B2',
    description_en: 'Care coordination and patient rights advocacy',
    description_pt: 'Coordenação de cuidados e defesa dos direitos do paciente',
  },
  // ──────────────────────────────────────────
  // HEALTH INFORMATICS & ADMINISTRATION
  // ──────────────────────────────────────────
  {
    id: 'health-informatics',
    name_en: 'Health Informatics',
    name_pt: 'Informática em Saúde',
    icon: Search,
    color: '#475569',
    description_en: 'Health data management and clinical systems',
    description_pt: 'Gestão de dados de saúde e sistemas clínicos',
  },
  {
    id: 'medical-coding',
    name_en: 'Medical Coding & Billing',
    name_pt: 'Codificação e Faturamento Médico',
    icon: Blend,
    color: '#64748B',
    description_en: 'Medical records coding and insurance billing',
    description_pt: 'Codificação de prontuários e faturamento de seguros',
  },
];

// Popular specialties shown in hero
export const POPULAR_SPECIALTIES = [
  'general-practice',
  'cardiology',
  'dermatology',
  'pediatrics',
  'dentistry',
];

// Legacy SERVICE_CATEGORIES for backwards compatibility
export const SERVICE_CATEGORIES = MEDICAL_CATEGORIES.map(cat => ({
  id: cat.id,
  name_pt: cat.name_pt,
  name_en: cat.name_en,
  icon: cat.icon,
  color: cat.color,
}));

// Consultation fee ranges — min/max values are in USD, converted to local currency at display time
export const CONSULTATION_FEE_RANGES = [
  { label: '$0 - $20', min: 0, max: 20 },
  { label: '$20 - $40', min: 20, max: 40 },
  { label: '$40 - $60', min: 40, max: 60 },
  { label: '$60 - $100', min: 60, max: 100 },
  { label: '$100 - $200', min: 100, max: 200 },
  { label: '$200+', min: 200, max: null },
  { label: 'Covered by insurance', min: null, max: null },
];

// Legacy CONSULTATION_FEES for backwards compatibility — min/max values in USD
export const CONSULTATION_FEES = [
  { id: 'under_20', label: 'Under $20', min: 0, max: 20 },
  { id: '20_40', label: '$20 - $40', min: 20, max: 40 },
  { id: '40_70', label: '$40 - $70', min: 40, max: 70 },
  { id: '70_100', label: '$70 - $100', min: 70, max: 100 },
  { id: '100_150', label: '$100 - $150', min: 100, max: 150 },
  { id: '150_200', label: '$150 - $200', min: 150, max: 200 },
  { id: 'above_200', label: 'Above $200', min: 200, max: null },
  { id: 'insurance', label: 'Insurance accepted', min: null, max: null },
] as const;

// Keep for backwards compatibility
export const BUDGET_RANGES = CONSULTATION_FEES;

// Appointment types
export const APPOINTMENT_TYPES = [
  { id: 'in-person', label_en: 'In-Person', label_pt: 'Presencial', label: 'Consultation', icon: Stethoscope },
  { id: 'teleconsultation', label_en: 'Video Call', label_pt: 'Videochamada', label: 'Teleconsultation', icon: Video },
  { id: 'phone', label_en: 'Phone Call', label_pt: 'Ligação', label: 'Follow-up', icon: Clock },
  { id: 'home-visit', label_en: 'Home Visit', label_pt: 'Visita Domiciliar', label: 'Check-up', icon: Shield },
] as const;

// Insurance providers (Brazil-specific)
export const INSURANCE_PROVIDERS = [
  'Unimed',
  'Bradesco Saúde',
  'Amil',
  'SulAmérica',
  'Hapvida',
  'NotreDame Intermédica',
  'Porto Seguro',
  'Prevent Senior',
  'Golden Cross',
  'Allianz',
  'Particular (Self-pay)',
] as const;

// Legacy COMMON_INSURANCE_PLANS for backwards compatibility
export const COMMON_INSURANCE_PLANS = INSURANCE_PROVIDERS;

export const URGENCY_LEVELS = [
  { id: 'emergency', label: 'Emergency', description: 'Within 24 hours' },
  { id: 'asap', label: 'Urgent', description: 'Within 1 week' },
  { id: 'flexible', label: 'Flexible', description: 'Within 1 month' },
  { id: 'scheduled', label: 'Scheduled', description: 'Specific date' },
] as const;

// Prices in USD — converted to local currency at display time
export const SUBSCRIPTION_TIERS = {
  free: {
    name: 'Basic',
    price: 0,
    canBid: false,
    portfolioPhotos: 5,
    portfolioVideos: 0,
    transactionFee: 7,
    features: [
      'Professional profile',
      'Appear in search results',
      'Receive direct appointment requests',
      'Up to 5 portfolio photos',
    ],
  },
  pro: {
    name: 'Pro',
    price: 29,
    canBid: true,
    bidsPerMonth: 20,
    maxBidAmount: 5000,
    portfolioPhotos: 20,
    portfolioVideos: 3,
    transactionFee: 5,
    features: [
      'Everything in Basic',
      'Accept appointment requests',
      'Up to 20 requests/month',
      'Up to 20 photos + 3 videos',
      'Calendar management',
      'Teleconsultation support',
    ],
  },
  elite: {
    name: 'Elite',
    price: 59,
    canBid: true,
    bidsPerMonth: -1,
    maxBidAmount: -1,
    portfolioPhotos: 50,
    portfolioVideos: 10,
    transactionFee: 4,
    features: [
      'Everything in Pro',
      'Unlimited appointment requests',
      'Featured in search results',
      'Elite badge on profile',
      'Advanced analytics',
      'Priority support',
    ],
  },
  enterprise: {
    name: 'Enterprise',
    price: 109,
    canBid: true,
    bidsPerMonth: -1,
    maxBidAmount: -1,
    portfolioPhotos: -1,
    portfolioVideos: -1,
    transactionFee: 3,
    features: [
      'Everything in Elite',
      'Instant notifications',
      'Smart scheduling',
      'Dedicated account manager',
      'API access',
      'Multi-location support',
    ],
  },
} as const;
