import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { getBaiseAppKey } from '@/lib/providerCommunication';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Trash2 } from 'lucide-react';

export function AccountDeletionCard({ onScheduled }:{onScheduled:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const requestDeletion=async()=>{const date=new Date(Date.now()+30*86400000).toLocaleDateString('pt-BR',{dateStyle:'long'});if(!window.confirm(`Excluir minha conta? A identidade compartilhada Casa, Medical e Legal Baise será programada para exclusão em ${date}. Você poderá recuperá-la antes dessa data. Registros exigidos por lei podem ser minimizados e mantidos pelo prazo aplicável.`))return;setBusy(true);const {data,error}=await supabase.functions.invoke('account-delete-request',{body:{appContext:getBaiseAppKey()}});setBusy(false);if(error){setMessage('Não foi possível programar a exclusão. Tente novamente.');return}setMessage(`Exclusão programada para ${new Date(data.scheduledPurgeAt).toLocaleDateString('pt-BR',{dateStyle:'long'})}.`);await onScheduled()};
  return <Card className="border-destructive/50"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base text-destructive"><Trash2 className="h-4 w-4"/>Excluir minha conta</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Esta ação fecha sua identidade inteira no Casa, Medical e Legal Baise. Você terá 30 dias para recuperar a conta. Registros legais, transacionais e, no Medical, dados de saúde sujeitos a obrigação legal podem ser minimizados e mantidos somente pelo prazo aplicável.</p><Button variant="destructive" className="w-full" disabled={busy} onClick={requestDeletion}>{busy?'Programando…':'Excluir minha conta'}</Button>{message&&<p className="text-sm" role="status">{message}</p>}</CardContent></Card>;
}

export function AccountRecoveryGate({ scheduledAt, onRecovered, closed = false }:{scheduledAt?:string|null;onRecovered:()=>Promise<void>;closed?:boolean}) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [date,setDate]=useState(scheduledAt||null);useEffect(()=>{if(date)return;void supabase.auth.getUser().then(async({data})=>{if(!data.user)return;const result=await supabase.from('account_deletion_requests').select('scheduled_purge_at').eq('user_id',data.user.id).eq('status','pending_deletion').order('requested_at',{ascending:false}).limit(1).maybeSingle();setDate(result.data?.scheduled_purge_at||null)})},[date]);const recover=async()=>{setBusy(true);const result=await supabase.functions.invoke('account-recover',{body:{appContext:getBaiseAppKey()}});setBusy(false);if(result.error){setError('Não foi possível recuperar a conta. Tente novamente.');return}await onRecovered()};
  return <main className="flex min-h-screen items-center justify-center bg-background p-6"><Card className="w-full max-w-lg"><CardHeader><CardTitle>{closed?'Sua conta foi encerrada':'Sua conta está programada para exclusão'}</CardTitle></CardHeader><CardContent className="space-y-4">{closed?<p>Esta conta foi encerrada e não pode mais acessar Casa, Medical ou Legal Baise.</p>:<><p>Sua identidade Casa, Medical e Legal Baise será excluída{date?` em ${new Date(date).toLocaleDateString('pt-BR',{dateStyle:'long'})}`:''}. Recupere-a agora com um clique.</p><p className="text-sm text-muted-foreground">Registros exigidos por lei, incluindo dados de saúde quando aplicável, podem ser minimizados e mantidos pelo prazo legal aplicável.</p><Button className="w-full" disabled={busy} onClick={recover}>{busy?'Recuperando…':'Recuperar conta'}</Button>{error&&<p className="text-sm text-destructive">{error}</p>}</>}</CardContent></Card></main>;
}
