export type BlogAudience = 'provider' | 'client';
export type BlogNiche = 'casa' | 'medical' | 'legal' | 'cross-platform';
export type BlogStatPreset = 'digital' | 'providerOps' | 'reviews' | 'medical' | 'legal' | 'payments' | 'growth';

export type BlogSource = {
  key: string;
  label: string;
  publisher: string;
  url: string;
};

export type BlogChartDatum = {
  label: string;
  value: number;
  display: string;
  note: string;
};

export type BlogTopicSeed = {
  audience: BlogAudience;
  slug: string;
  title: string;
  niche: BlogNiche;
  category: string;
  searchIntent: string;
  promise: string;
  platformUse: string;
  statPreset: BlogStatPreset;
  actions: string[];
  sourceKeys: string[];
};

export type BaiseBlogPost = BlogTopicSeed & {
  id: string;
  number: number;
  readTime: string;
  deck: string;
  story: string;
  lesson: string;
  strategy: string;
  dataNarrative: string;
  chartTitle: string;
  chartData: BlogChartDatum[];
  sources: BlogSource[];
  ctaTitle: string;
  ctaText: string;
};

export const BLOG_CONTENT_RATIO = [
  { label: 'Practical education', value: 40 },
  { label: 'Trust and vetting', value: 25 },
  { label: 'Platform workflow', value: 20 },
  { label: 'Data and resources', value: 10 },
  { label: 'CTA', value: 5 },
] as const;

export const BLOG_SOURCES: Record<string, BlogSource> = {
  datareportalBrazil2026: {
    key: 'datareportalBrazil2026',
    label: 'Digital 2026: Brazil',
    publisher: 'DataReportal',
    url: 'https://datareportal.com/reports/digital-2026-brazil',
  },
  sebraeWhatsappServices: {
    key: 'sebraeWhatsappServices',
    label: 'WhatsApp is the main communication channel for 80% of service businesses',
    publisher: 'Agência Sebrae de Noticias',
    url: 'https://agenciasebrae.com.br/cultura-empreendedora/whatsapp-e-o-principal-meio-de-comunicação-para-80-dos-negócios-de-serviço/',
  },
  sebraePaidAds: {
    key: 'sebraePaidAds',
    label: 'Small businesses invest more in digital advertising',
    publisher: 'Conselho Digital do Brasil / Sebrae summary',
    url: 'https://conselhodigital.org.br/2025/02/pequenos-negocios-investem-cada-vez-mais-em-publicidade-digital-aponta-pesquisa-do-sebrae/',
  },
  brazilReviews2025: {
    key: 'brazilReviews2025',
    label: '96% of consumers read Google reviews before buying',
    publisher: 'Mercado & Consumo / Reclame Aqui and Harmo',
    url: 'https://mercadoeconsumo.com.br/26/03/2025/noticias-varejo/reclame-aqui-96-dos-consumidores-leem-avaliações-no-google-antes-de-comprar/',
  },
  brightLocalReviews2025: {
    key: 'brightLocalReviews2025',
    label: 'Local Consumer Review Survey 2025',
    publisher: 'BrightLocal',
    url: 'https://www.brightlocal.com/research/local-consumer-review-survey-2025/',
  },
  googleReviewTips: {
    key: 'googleReviewTips',
    label: 'Tips to get more reviews',
    publisher: 'Google Business Profile Help',
    url: 'https://support.google.com/business/answer/3474122?hl=en',
  },
  medicalDemographics2025: {
    key: 'medicalDemographics2025',
    label: 'Medical Demography in Brazil 2025',
    publisher: 'FMUSP, Ministry of Health, AMB',
    url: 'https://www.fm.usp.br/fmusp/noticias/ministerio-da-saúde-fmusp-e-amb-lancam-a-demografia-médica-no-brasil-2025',
  },
  ansSectorData2026: {
    key: 'ansSectorData2026',
    label: 'Private health plan beneficiaries in Brazil',
    publisher: 'ANS',
    url: 'https://www.gov.br/ans/pt-br/acesso-a-informação/perfil-do-setor/dados-gerais',
  },
  oabLawyerRegistry: {
    key: 'oabLawyerRegistry',
    label: 'Brazilian lawyer registry totals',
    publisher: 'OAB Nacional',
    url: 'https://www.oab.org.br/institucionalconselhofederal/quadroadvogados',
  },
  cnjJusticeNumbers2025: {
    key: 'cnjJusticeNumbers2025',
    label: 'Justica em Numeros 2025',
    publisher: 'CNJ',
    url: 'https://www.cnj.jus.br/pesquisas-judiciarias/justica-em-numeros/',
  },
};

const CHART_PRESETS: Record<BlogStatPreset, { title: string; narrative: string; data: BlogChartDatum[] }> = {
  digital: {
    title: 'Brazil is a mobile-first, social-discovery market.',
    narrative:
      'Brazilian clients and providers are already searching, comparing, watching, and messaging online. Education content should help them make better decisions inside that behavior instead of asking them to leave it.',
    data: [
      { label: 'Internet users', value: 185, display: '185M', note: 'DataReportal, late 2025 estimate' },
      { label: 'Social identities', value: 150, display: '150M', note: 'DataReportal, October 2025' },
      { label: 'Mobile connections', value: 217, display: '217M', note: 'DataReportal, late 2025' },
      { label: 'YouTube reach', value: 150, display: '150M', note: 'DataReportal / Google ad planning' },
    ],
  },
  providerOps: {
    title: 'Service businesses communicate constantly, but CRM discipline is still rare.',
    narrative:
      'Sebrae reported WhatsApp as the main client communication channel for more than 80% of service businesses, while CRM importance was cited by only 6% on average. That gap is exactly where Baise can help providers become more organized and more trusted.',
    data: [
      { label: 'WhatsApp use by service businesses', value: 80, display: '80%+', note: 'Sebrae Pesquisa Serviço 2025' },
      { label: 'In-person still important', value: 56, display: '56%', note: 'Sebrae service-business research' },
      { label: 'CRM importance cited', value: 6, display: '6%', note: 'Brazil average in Sebrae article' },
      { label: 'CRM importance in Southeast', value: 2, display: '2%', note: 'Sudeste reference in Sebrae article' },
    ],
  },
  reviews: {
    title: 'Reviews are a decision layer, not decoration.',
    narrative:
      'Brazilian consumers use reviews to shortlist providers, clinics, offices, and stores. The goal is not to chase stars; it is to make real service quality visible with verified records, timely responses, and proof of work.',
    data: [
      { label: 'Read Google reviews', value: 96, display: '96%', note: 'Reclame Aqui / Harmo survey reported by Mercado & Consumo' },
      { label: 'Discard below 4 stars', value: 90, display: '9 in 10', note: 'Google-rating behavior in the same survey' },
      { label: 'Require at least 10 reviews', value: 43, display: '43%', note: 'Minimum-review threshold in the survey' },
      { label: 'Responses matter', value: 76.5, display: '76.5%', note: 'Company replies influence choice' },
    ],
  },
  medical: {
    title: 'Medical choice needs access, specialty clarity, and records.',
    narrative:
      'Brazil has a large and growing medical market, but patients still need help understanding specialties, coverage, follow-up, documentation, and communication. MD Baise content should teach patients how to choose with calm clarity.',
    data: [
      { label: 'Specialist physicians', value: 59.1, display: '59.1%', note: 'Medical Demography in Brazil 2025' },
      { label: 'Generalist physicians', value: 40.9, display: '40.9%', note: 'Medical Demography in Brazil 2025' },
      { label: 'Medical plan beneficiaries', value: 52.9, display: '52.9M', note: 'ANS, March 2026' },
      { label: 'Dental plan beneficiaries', value: 35.8, display: '35.8M', note: 'ANS, March 2026' },
    ],
  },
  legal: {
    title: 'Legal choice needs credential checks, scope, and written records.',
    narrative:
      'Brazil has a deep legal-services market. Clients need help distinguishing the right specialty, confirming professional registration, understanding scope, and keeping every agreement, invoice, and document easy to retrieve.',
    data: [
      { label: 'Regular lawyers', value: 1498, display: '1.49M', note: 'OAB registry total' },
      { label: 'Total OAB records', value: 1606, display: '1.60M', note: 'OAB registry including categories' },
      { label: 'Sao Paulo total records', value: 411, display: '411K', note: 'OAB Sao Paulo line item' },
      { label: 'Rio de Janeiro total records', value: 174, display: '174K', note: 'OAB Rio de Janeiro line item' },
    ],
  },
  payments: {
    title: 'Payment confidence comes from options, records, and timing.',
    narrative:
      'For services, the payment question is rarely only price. Clients need proof, invoices, refunds, milestones, and receipts. Providers need clean books, transaction history, and fewer disputes.',
    data: [
      { label: 'Receipt clarity', value: 95, display: 'High', note: 'Illustrative Baise operating goal' },
      { label: 'Milestone visibility', value: 88, display: 'High', note: 'Illustrative Baise operating goal' },
      { label: 'Refund decision trail', value: 82, display: 'High', note: 'Illustrative Baise operating goal' },
      { label: 'Off-platform confusion', value: 31, display: 'Lower', note: 'Illustrative Baise reduction target' },
    ],
  },
  growth: {
    title: 'Growth improves when marketing, operations, and proof are connected.',
    narrative:
      'Providers do not need more random tools. They need a rhythm: attract the right lead, answer quickly, quote clearly, deliver visibly, request feedback, and use the history to win the next client.',
    data: [
      { label: 'Paid digital ads adoption', value: 48, display: '48%', note: 'Sebrae Pulse summary' },
      { label: 'Online promotion use', value: 59, display: '59%', note: 'Sebrae Pulse summary' },
      { label: 'Digital selling tools', value: 70, display: '70%', note: 'Sebrae Pulse summary' },
      { label: 'Instagram business use', value: 60, display: '60%', note: 'Sebrae Pulse summary' },
    ],
  },
};

const providerTopics: Omit<BlogTopicSeed, 'audience'>[] = [
  { slug: 'provider-profile-client-winning-storefront', title: 'How to turn your Baise profile into a client-winning storefront', niche: 'cross-platform', category: 'Trust and profile', searchIntent: 'get more clients with a better profile', promise: 'make your profile prove reliability before the first message', platformUse: 'profile photos, verified badge, service menu, portfolio, ratings, and response expectations', statPreset: 'reviews', actions: ['Lead with the exact service outcome you deliver.', 'Add proof of work, credentials, and service boundaries.', 'Use plain pricing ranges or consultation steps where exact pricing depends on scope.', 'Refresh reviews and photos monthly.'], sourceKeys: ['brazilReviews2025', 'googleReviewTips'] },
  { slug: 'provider-verified-badge-background-checks', title: 'Why a verified badge helps good providers win faster', niche: 'cross-platform', category: 'Trust and profile', searchIntent: 'verified service provider badge benefits', promise: 'turn verification into a simple trust signal', platformUse: 'background-check status, identity verification, license notes, and rating thresholds', statPreset: 'reviews', actions: ['Explain what is verified in simple language.', 'Keep documents current before campaigns go live.', 'Pair the badge with recent reviews and completed-work proof.', 'Treat verification as a conversion asset, not a decoration.'], sourceKeys: ['brazilReviews2025', 'brightLocalReviews2025'] },
  { slug: 'provider-reviews-response-system', title: 'A simple review response system for service providers', niche: 'cross-platform', category: 'Reputation', searchIntent: 'how providers should respond to reviews', promise: 'convert real feedback into credibility', platformUse: 'review requests, response templates, testimonial approvals, and service-history links', statPreset: 'reviews', actions: ['Respond quickly and specifically.', 'Thank clients for concrete details instead of generic praise.', 'Use private portal messages for problem resolution.', 'Ask for reviews after completion, not before the client has proof.'], sourceKeys: ['brazilReviews2025', 'brightLocalReviews2025', 'googleReviewTips'] },
  { slug: 'provider-quote-management-that-closes', title: 'Quote management that closes jobs without confusing clients', niche: 'cross-platform', category: 'Quotes and sales', searchIntent: 'how to send service quotes', promise: 'make the next step obvious and documented', platformUse: 'quote builder, line items, client questions, expiration dates, and approval tracking', statPreset: 'payments', actions: ['Use one clear scope per quote.', 'Separate required work from optional add-ons.', 'Add photos, assumptions, and timing.', 'Turn accepted quotes into invoices without retyping details.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-invoice-receipt-accounting-basics', title: 'Invoicing and receipts that make your business easier to run', niche: 'cross-platform', category: 'Finance', searchIntent: 'service provider invoicing receipts Brazil', promise: 'keep every transaction ready for clients, taxes, and internal review', platformUse: 'unique invoice IDs, client IDs, timestamps, receipts, tax records, and branded invoice downloads', statPreset: 'payments', actions: ['Use a unique invoice for every transaction.', 'Attach service description, time, date, payment status, and photos when needed.', 'Download monthly and annual records.', 'Keep refunds, credits, and balance transfers tied to the original invoice.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-recurring-one-off-payment-options', title: 'How to offer recurring, one-off, and milestone payments with confidence', niche: 'cross-platform', category: 'Payments', searchIntent: 'recurring payments service business', promise: 'match payment structure to how the service is actually delivered', platformUse: 'one-off checkout, subscriptions, weekly or monthly billing, milestone schedules, and payment-plan notes', statPreset: 'payments', actions: ['Choose one-off payment for clear, single-scope services.', 'Use recurring billing for maintenance, care, retainers, or weekly service.', 'Use milestones when delivery depends on phases.', 'Put the payment timeline inside the client portal.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-pos-on-site-payment-workflow', title: 'How POS payments help providers collect cleanly on site', niche: 'cross-platform', category: 'Payments', searchIntent: 'service business POS payments on site', promise: 'accept payments where the service happens while keeping the record clean', platformUse: 'POS payment capture, receipt generation, internal balance, and transaction history', statPreset: 'payments', actions: ['Confirm scope before collecting payment.', 'Issue a receipt immediately.', 'Attach the payment to the correct job and client ID.', 'Use portal messages for any payment change.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-refunds-service-credits-policy', title: 'Refunds vs service credits: how to keep clients calm and books clean', niche: 'cross-platform', category: 'Payments', searchIntent: 'refund service credit policy providers', promise: 'turn disputes into documented decisions', platformUse: 'refund request, service credit, internal balance, and review item tracking', statPreset: 'payments', actions: ['Define when a full refund is appropriate.', 'Offer service credit when future work can solve the issue.', 'Keep every decision tied to the original invoice.', 'Flag chargebacks for internal review.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-subcontractor-management-books', title: 'Subcontractor management without losing control of payments and books', niche: 'casa', category: 'Operations', searchIntent: 'manage subcontractors service business accounting', promise: 'hire help while preserving client trust and accounting clarity', platformUse: 'subcontractor assignments, benchmark releases, balance transfers, photos, signatures, and accounting notes', statPreset: 'payments', actions: ['Define who owns the client relationship.', 'Set release benchmarks before work begins.', 'Let subcontractors collect only through approved workflows.', 'Keep subcontractor payments separate from client-facing receipts.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-calendar-manager-bookings', title: 'A calendar rhythm for bookings, cancellations, follow-ups, and campaigns', niche: 'cross-platform', category: 'Calendar', searchIntent: 'calendar management service providers', promise: 'stop losing work because timing lives in scattered chats', platformUse: 'calendar manager, booking status, cancellations, follow-ups, reminders, campaign dates, and notification rules', statPreset: 'providerOps', actions: ['Put every appointment on the platform calendar.', 'Use cancellation reasons to improve scheduling.', 'Schedule follow-ups before closing the job.', 'Add campaign send dates to the same operating calendar.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-crm-intake-followup-system', title: 'The CRM system every service provider needs before buying more ads', niche: 'cross-platform', category: 'CRM', searchIntent: 'CRM for small service providers Brazil', promise: 'organize leads, clients, follow-ups, and service history in one place', platformUse: 'CRM profiles, source tracking, notes, tasks, campaigns, and next-best action queues', statPreset: 'providerOps', actions: ['Capture source, need, urgency, budget, and language.', 'Assign the next step immediately.', 'Track why leads convert or stall.', 'Use saved views for hot leads and overdue follow-ups.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-client-insight-surveys', title: 'Client insight surveys that reveal what service to offer next', niche: 'cross-platform', category: 'CRM', searchIntent: 'client survey service business upsells', promise: 'learn enough to recommend value instead of pushing volume', platformUse: 'survey answers, demographics, occupation, family size, life goals, revenue, and product-fit scoring', statPreset: 'growth', actions: ['Ask only questions that improve service.', 'Store answers on the client profile.', 'Use answers to recommend helpful add-ons.', 'Refresh surveys after major life or business changes.'], sourceKeys: ['sebraePaidAds', 'sebraeWhatsappServices'] },
  { slug: 'provider-email-campaigns-service-business', title: 'Email campaigns that educate clients before they need urgent help', niche: 'cross-platform', category: 'Campaigns', searchIntent: 'email campaigns for service businesses', promise: 'send value-based messages that make clients more prepared', platformUse: 'branded email templates, segments, triggers, reminders, confirmations, and lifecycle campaigns', statPreset: 'growth', actions: ['Write one campaign per client need.', 'Use subject lines that promise a useful next step.', 'Trigger reminders from service status changes.', 'Measure replies and bookings, not just sends.'], sourceKeys: ['sebraePaidAds', 'datareportalBrazil2026'] },
  { slug: 'provider-whatsapp-campaigns-without-chaos', title: 'WhatsApp campaigns without turning your business into chaos', niche: 'cross-platform', category: 'Campaigns', searchIntent: 'WhatsApp campaigns service providers Brazil', promise: 'use WhatsApp where it helps while keeping the official record in Baise', platformUse: 'WhatsApp opt-ins, portal-first messaging, campaign templates, status updates, and opt-out preferences', statPreset: 'providerOps', actions: ['Reserve WhatsApp for reminders and useful nudges.', 'Keep detailed files, payments, and decisions in the portal.', 'Use approved templates for recurring messages.', 'Respect opt-outs for non-email channels.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-push-notification-strategy', title: 'Push notifications that move work forward without annoying clients', niche: 'cross-platform', category: 'Campaigns', searchIntent: 'push notifications service provider app', promise: 'make notifications useful enough that clients keep them on', platformUse: 'push preferences, service milestones, payment reminders, document requests, and booking alerts', statPreset: 'providerOps', actions: ['Notify only when action is needed.', 'Make every notification link to the right portal screen.', 'Avoid duplicate reminders across channels.', 'Let clients opt out of push, SMS, and WhatsApp.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-project-management-proof', title: 'Project management that proves what happened, when, and why', niche: 'casa', category: 'Projects', searchIntent: 'project management for service providers', promise: 'replace scattered updates with visible progress', platformUse: 'project stages, tasks, photos, unexpected-problem notes, client approvals, and completion status', statPreset: 'payments', actions: ['Break larger jobs into phases.', 'Attach photos to each major milestone.', 'Document unexpected problems before changing price or scope.', 'Request sign-off before closing the project.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-photo-proof-signoff', title: 'Photo proof and client sign-off: the simplest dispute prevention habit', niche: 'casa', category: 'Projects', searchIntent: 'photo proof client sign off service work', promise: 'show completed work and protect both sides', platformUse: 'photo uploads, work-completed albums, issue photos, signatures, and quote attachments', statPreset: 'payments', actions: ['Capture before, during, and after photos.', 'Label photos with the service stage.', 'Attach proof to quotes and invoices.', 'Ask for sign-off while the work is fresh.'], sourceKeys: ['brightLocalReviews2025'] },
  { slug: 'provider-document-vault-for-service-business', title: 'Why your service business needs a document vault', niche: 'cross-platform', category: 'Records', searchIntent: 'document vault service business client files', promise: 'make every file retrievable when money, taxes, or proof matter', platformUse: 'client-scoped vault, categories, preview, reclassification, parser review, and sign-off', statPreset: 'payments', actions: ['Create one vault folder per client.', 'Separate quotes, invoices, photos, signatures, IDs, and tax records.', 'Use staff review before relying on parsed data.', 'Give clients access only to clean client-facing files.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-tax-record-tracking', title: 'Tax record tracking for providers who want clean books all year', niche: 'cross-platform', category: 'Finance', searchIntent: 'tax records service provider invoices receipts', promise: 'stop treating tax season as a search mission', platformUse: 'transaction history, invoice IDs, receipt exports, quarterly downloads, and accounting tags', statPreset: 'payments', actions: ['Tag every transaction by service and client.', 'Download monthly and quarterly records.', 'Separate payouts, refunds, credits, and subcontractor transfers.', 'Keep client-facing receipts clean and internal notes private.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-ceo-metrics-dashboard', title: 'The seven CEO metrics a service provider should actually watch', niche: 'cross-platform', category: 'Analytics', searchIntent: 'service provider dashboard metrics', promise: 'run the business by signal, not emotion', platformUse: 'dashboard KPIs, conversion rate, repeat bookings, response speed, revenue, reviews, retention, and campaign ROI', statPreset: 'growth', actions: ['Review lead volume and conversion weekly.', 'Track average time to quote and time to payment.', 'Watch repeat bookings and review response rate.', 'Connect campaigns to actual revenue.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-social-content-that-converts', title: 'Social content that converts because it teaches, not because it shouts', niche: 'cross-platform', category: 'Marketing', searchIntent: 'social media content service providers', promise: 'turn expertise into useful posts clients can trust', platformUse: 'Postiz integration, content calendar, UGC campaigns, review snippets, and campaign attribution', statPreset: 'digital', actions: ['Post client questions as educational content.', 'Show process and proof, not only final results.', 'Connect every campaign to a tracked link.', 'Use social analytics to double down on what earns trust.'], sourceKeys: ['datareportalBrazil2026', 'sebraePaidAds'] },
  { slug: 'provider-influencer-partner-referrals', title: 'How partners and influencers can send better-fit clients to your service', niche: 'cross-platform', category: 'Growth', searchIntent: 'partner referral campaigns service providers', promise: 'make referrals measurable without making them messy', platformUse: 'unique links, QR codes, codes, campaign rules, referral status, and conversion tracking', statPreset: 'growth', actions: ['Give partners a simple offer to explain.', 'Track every lead source automatically.', 'Keep pricing promises inside approved rules.', 'Use referral status updates to keep partners engaged.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-google-reviews-after-service', title: 'How to ask for Google reviews after a real service experience', niche: 'cross-platform', category: 'Reputation', searchIntent: 'ask customers for Google reviews service business', promise: 'request reviews at the right time and with the right context', platformUse: 'testimonial request page, Google review CTA, video testimonial upload, and approval workflow', statPreset: 'reviews', actions: ['Ask after completion and sign-off.', 'Make the request short and specific.', 'Never pressure a client to say something untrue.', 'Respond to reviews with care and professionalism.'], sourceKeys: ['googleReviewTips', 'brazilReviews2025'] },
  { slug: 'provider-home-repair-bookings', title: 'How home repair providers can win clients who are nervous about quality', niche: 'casa', category: 'Casa services', searchIntent: 'home repair service provider trust Brazil', promise: 'make reliability visible before the appointment', platformUse: 'photos, service categories, scheduling, quote approvals, proof of work, and verified reviews', statPreset: 'reviews', actions: ['Show similar completed work.', 'Explain materials and timing clearly.', 'Document changes before doing extra work.', 'Close with a receipt and review request.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'provider-cleaning-recurring-services', title: 'Recurring cleaning services: how to package trust, timing, and value', niche: 'casa', category: 'Casa services', searchIntent: 'recurring cleaning service subscriptions', promise: 'turn one good job into a predictable client relationship', platformUse: 'recurring bookings, subscription billing, checklists, reminders, and review history', statPreset: 'payments', actions: ['Create weekly, biweekly, and monthly service options.', 'Use checklists for consistency.', 'Confirm access and supplies in the portal.', 'Review satisfaction every month.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-renovation-milestone-payments', title: 'Renovation milestone payments that protect providers and clients', niche: 'casa', category: 'Casa services', searchIntent: 'renovation milestone payments Brazil', promise: 'connect payment releases to visible progress', platformUse: 'project stages, benchmark payments, subcontractor releases, inspection photos, and sign-off', statPreset: 'payments', actions: ['Break the renovation into measurable stages.', 'Attach photos and inspection notes to every stage.', 'Require sign-off before release.', 'Keep change orders separate from original scope.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-home-inspection-reports', title: 'Home inspection reports that clients can understand and act on', niche: 'casa', category: 'Casa services', searchIntent: 'home inspection report service provider', promise: 'turn technical findings into a clear decision tool', platformUse: 'photo upload, issue categories, quote attachments, follow-up tasks, and downloadable reports', statPreset: 'reviews', actions: ['Use plain language beside technical terms.', 'Rank issues by urgency.', 'Attach photos and location notes.', 'Offer next-step options without pressure.'], sourceKeys: ['brightLocalReviews2025'] },
  { slug: 'provider-medical-profile-specialty-trust', title: 'Medical provider profiles: how to explain specialty, access, and follow-up', niche: 'medical', category: 'Medical services', searchIntent: 'medical provider profile patient trust', promise: 'help patients choose care with less confusion', platformUse: 'specialty notes, credentials, consultation types, follow-up instructions, and patient history', statPreset: 'medical', actions: ['Explain the conditions you commonly support.', 'Show credentials and languages clearly.', 'Set expectations for documents and follow-up.', 'Keep patient communications inside secure channels.'], sourceKeys: ['medicalDemographics2025', 'ansSectorData2026'] },
  { slug: 'provider-doctor-verification-patient-confidence', title: 'How doctor verification builds patient confidence before booking', niche: 'medical', category: 'Medical services', searchIntent: 'doctor verification patient confidence Brazil', promise: 'make credentials easy to understand', platformUse: 'verified badges, license notes, specialty categories, reviews, and appointment records', statPreset: 'medical', actions: ['Display verification where patients decide.', 'Explain what documents patients should bring.', 'Clarify whether the visit is urgent, routine, or follow-up.', 'Use post-visit summaries for continuity.'], sourceKeys: ['medicalDemographics2025'] },
  { slug: 'provider-medical-followup-campaigns', title: 'Medical follow-up campaigns that feel caring, not automated', niche: 'medical', category: 'Medical services', searchIntent: 'medical follow up reminders patient portal', promise: 'support patients after the visit with clear next steps', platformUse: 'follow-up reminders, portal messages, document requests, appointment calendar, and push notifications', statPreset: 'medical', actions: ['Use reminders for care steps the patient already expects.', 'Keep sensitive information inside the portal.', 'Make rescheduling easy.', 'Track missed follow-ups for staff review.'], sourceKeys: ['ansSectorData2026'] },
  { slug: 'provider-legal-consultation-intake', title: 'Legal consultation intake that saves time and earns trust', niche: 'legal', category: 'Legal services', searchIntent: 'legal consultation intake client questions', promise: 'prepare clients before the first meeting', platformUse: 'intake forms, document vault, conflict notes, appointment calendar, and secure messaging', statPreset: 'legal', actions: ['Ask for timeline, parties, documents, and urgency.', 'Tell clients what not to upload publicly.', 'Separate legal advice from educational content.', 'Keep the consultation summary organized.'], sourceKeys: ['oabLawyerRegistry', 'cnjJusticeNumbers2025'] },
  { slug: 'provider-legal-retainers-invoices-records', title: 'Retainers, invoices, and records for legal providers', niche: 'legal', category: 'Legal services', searchIntent: 'legal retainer invoice records Brazil', promise: 'make every paid step clear and retrievable', platformUse: 'retainer records, invoices, payment status, document vault, task notes, and client-facing receipts', statPreset: 'payments', actions: ['Separate retainer scope from extra work.', 'Use invoice IDs for every payment.', 'Keep privileged notes internal.', 'Give clients clean receipts and status updates.'], sourceKeys: ['oabLawyerRegistry'] },
  { slug: 'provider-bilingual-service-listings', title: 'Bilingual service listings for Brazilian and international clients', niche: 'cross-platform', category: 'International clients', searchIntent: 'bilingual service listing Brazil providers', promise: 'make your service understandable across language barriers', platformUse: 'English, Portuguese, and Spanish service descriptions, language preferences, and translated campaign copy', statPreset: 'digital', actions: ['State languages clearly.', 'Avoid local jargon without explanation.', 'Use examples that international clients understand.', 'Confirm preferred language before sending reminders.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-international-client-onboarding', title: 'International client onboarding: what to explain before the work starts', niche: 'cross-platform', category: 'International clients', searchIntent: 'onboard international clients Brazil service provider', promise: 'reduce confusion around documents, payments, timing, and expectations', platformUse: 'intake, portal messages, translated files, payment options, and status dashboards', statPreset: 'digital', actions: ['Explain local process steps.', 'Use written summaries after calls.', 'Confirm currency, timing, and documents.', 'Keep every decision in the portal.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-pricing-transparency', title: 'Pricing transparency without boxing yourself into the wrong scope', niche: 'cross-platform', category: 'Sales', searchIntent: 'service provider pricing transparency', promise: 'give clients confidence without overpromising', platformUse: 'service menus, estimate ranges, quote assumptions, add-ons, coupons, and payment plans', statPreset: 'payments', actions: ['Show starting points where possible.', 'Explain what changes price.', 'Use quotes for variable work.', 'Offer add-ons only when they solve a real client need.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'provider-coupons-offers-premium', title: 'Coupons and offers that bring in serious clients, not bargain chaos', niche: 'cross-platform', category: 'Promotions', searchIntent: 'service provider coupons offers strategy', promise: 'use promotions to introduce value without discounting your reputation', platformUse: 'coupon codes, referral links, campaign rules, premium trials, and conversion tracking', statPreset: 'growth', actions: ['Attach every offer to a campaign.', 'Define eligibility and expiration clearly.', 'Track whether discounted clients become repeat clients.', 'Avoid offers that cheapen complex services.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-referral-program-growth', title: 'How to use referrals as a growth engine without losing attribution', niche: 'cross-platform', category: 'Referrals', searchIntent: 'referral program service providers', promise: 'reward trust while tracking who created it', platformUse: 'client referral links, QR codes, client IDs, referral status, credit eligibility, and email triggers', statPreset: 'growth', actions: ['Give every client a unique link and code.', 'Show referral status in plain language.', 'Apply credits only after qualification rules are met.', 'Send thank-you messages at each milestone.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-sponsor-ready-social-analytics', title: 'Sponsor-ready social analytics for providers and creators', niche: 'cross-platform', category: 'Marketing', searchIntent: 'social analytics service provider sponsors', promise: 'show reach, engagement, and conversion in one clean story', platformUse: 'advanced social analytics, UGC campaign tracking, sponsor metrics, and campaign attribution', statPreset: 'digital', actions: ['Track reach and engagement by campaign.', 'Separate vanity metrics from conversion metrics.', 'Use client-safe testimonials and photos.', 'Create monthly sponsor-ready reports.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-postiz-social-scheduling', title: 'A simple Postiz scheduling rhythm for service providers', niche: 'cross-platform', category: 'Marketing', searchIntent: 'Postiz social scheduling service providers', promise: 'plan useful content before the week gets busy', platformUse: 'Postiz integration, content queue, campaign dates, referral links, and analytics', statPreset: 'growth', actions: ['Batch educational posts once a week.', 'Use one CTA per post.', 'Schedule proof-of-work posts after approval.', 'Review which posts create portal actions.'], sourceKeys: ['sebraePaidAds', 'datareportalBrazil2026'] },
  { slug: 'provider-ai-api-keys-safe-workflows', title: 'AI API keys and safe workflows for service providers', niche: 'cross-platform', category: 'AI and integrations', searchIntent: 'AI integration service provider API keys', promise: 'use AI to draft, summarize, and organize without losing control of client data', platformUse: 'API key generation, AI tool settings, audit logs, prompt permissions, and staff access controls', statPreset: 'growth', actions: ['Use AI for drafts, summaries, and templates.', 'Keep sensitive client facts permissioned.', 'Review AI output before sending.', 'Rotate and revoke keys when staff access changes.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-accounting-integrations-quickbooks-plaid', title: 'Accounting integrations: what providers should prepare before syncing books', niche: 'cross-platform', category: 'Integrations', searchIntent: 'QuickBooks Plaid service provider accounting integration', promise: 'make future accounting sync cleaner by structuring records now', platformUse: 'transaction IDs, categories, payout records, refunds, credits, and accounting exports', statPreset: 'payments', actions: ['Clean up categories before syncing.', 'Separate client payments from provider payouts.', 'Keep refund and credit records attached to source invoices.', 'Review monthly exports before tax season.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-google-microsoft-gmail-integrations', title: 'Google, Microsoft, and Gmail integrations that reduce duplicate work', niche: 'cross-platform', category: 'Integrations', searchIntent: 'Gmail Microsoft Google integrations service business', promise: 'connect the tools providers already use without making the portal optional', platformUse: 'calendar sync, email actions, document links, campaign triggers, and portal-first messaging', statPreset: 'providerOps', actions: ['Sync calendars but manage service status in Baise.', 'Use email for notifications, not hidden decisions.', 'Store documents in the correct client record.', 'Keep opt-out rules clear by channel.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-campaign-calendar-planning', title: 'The monthly campaign calendar every provider should keep', niche: 'cross-platform', category: 'Campaigns', searchIntent: 'monthly campaign calendar service provider', promise: 'plan reminders, follow-ups, offers, and content without scrambling', platformUse: 'campaign calendar, email sequences, WhatsApp reminders, push notices, and social scheduling', statPreset: 'growth', actions: ['Pick one client problem per campaign.', 'Schedule content, email, and follow-up tasks together.', 'Measure appointment requests and quotes.', 'Archive what worked for future reuse.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-operating-queue', title: 'An operating queue that tells providers what needs attention first', niche: 'cross-platform', category: 'Operations', searchIntent: 'service business operating queue tasks', promise: 'stop letting urgent work hide inside inboxes', platformUse: 'money blocked, unsigned agreements, missing documents, overdue quotes, referral outreach, and testimonial reviews', statPreset: 'providerOps', actions: ['Group tasks by urgency.', 'Assign one owner per next step.', 'Link every task to a client, quote, payment, or project.', 'Close the loop with a status update.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-quality-control-score', title: 'Quality control score: a readiness check before clients feel friction', niche: 'cross-platform', category: 'Operations', searchIntent: 'quality control score service provider CRM', promise: 'catch missing details before they become lost clients', platformUse: 'profile completeness, contact verification, language, source, next action, duplicate warnings, and consent', statPreset: 'providerOps', actions: ['Review readiness weekly.', 'Fix missing contact and language data first.', 'Resolve duplicate records before payouts or credits.', 'Use score changes to coach staff.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-service-recovery-response', title: 'Service recovery: what to do when a job goes off plan', niche: 'cross-platform', category: 'Operations', searchIntent: 'service recovery unhappy client provider', promise: 'turn problems into documented decisions and fair next steps', platformUse: 'issue notes, photo proof, credit options, refund review, client messages, and internal tasks', statPreset: 'payments', actions: ['Document the problem quickly.', 'Separate facts from feelings.', 'Offer a repair, credit, or refund path when appropriate.', 'Close with a written summary.'], sourceKeys: ['brightLocalReviews2025'] },
  { slug: 'provider-no-show-cancellation-policy', title: 'No-shows and cancellations: a policy that protects everyone', niche: 'cross-platform', category: 'Operations', searchIntent: 'service provider cancellation no show policy', promise: 'reduce lost time while staying fair to clients', platformUse: 'booking terms, reminders, cancellation reasons, reschedule links, and payment holds', statPreset: 'payments', actions: ['State the policy before booking.', 'Send reminders with reschedule links.', 'Track cancellation reasons.', 'Make exceptions visible and consistent.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-loyalty-recurring-client-base', title: 'How to build a recurring client base without feeling salesy', niche: 'cross-platform', category: 'Retention', searchIntent: 'recurring clients service provider retention', promise: 'use service history to offer useful care at the right time', platformUse: 'recurring services, annual reviews, coupons, reminders, surveys, and product-fit recommendations', statPreset: 'growth', actions: ['Offer maintenance before emergencies.', 'Use client history to personalize reminders.', 'Let clients request add-ons without pressure.', 'Measure retention by service type.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-product-add-on-recommendations', title: 'How to recommend add-ons based on value, not pressure', niche: 'cross-platform', category: 'Product intelligence', searchIntent: 'service provider add on recommendations', promise: 'suggest the next useful service only when it fits the client', platformUse: 'product catalog, client fit score, recommended add-ons, value emails, and quote creation', statPreset: 'growth', actions: ['Connect recommendations to a real client need.', 'Explain the value in plain language.', 'Let clients request more information before buying.', 'Track accepted, declined, and not-now outcomes.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-service-menu-product-catalog', title: 'Build a service menu that staff, partners, and clients can understand', niche: 'cross-platform', category: 'Product intelligence', searchIntent: 'service menu product catalog providers', promise: 'make every offer clear enough to sell and deliver consistently', platformUse: 'product tab, service descriptions, pricing notes, eligibility rules, and partner-safe recommendations', statPreset: 'growth', actions: ['Name each service by the outcome it creates.', 'Define who it is for and who it is not for.', 'Add delivery steps and required documents.', 'Review product performance monthly.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-payout-receipts-partner-cleanup', title: 'Partner payout receipts that keep growth programs clean', niche: 'cross-platform', category: 'Partners', searchIntent: 'partner payout receipts referral program', promise: 'pay partners clearly without overloading them with internal math', platformUse: 'partner campaigns, payout history, monthly receipts, tax exports, unique links, QR codes, and codes', statPreset: 'growth', actions: ['Show clicks, leads, conversions, and payout amount.', 'Generate receipts by month, quarter, and year.', 'Keep internal expenses hidden from partner dashboards.', 'Flag duplicates before payout.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'provider-portal-first-communication', title: 'Portal-first communication: how to keep clients from leaving the system', niche: 'cross-platform', category: 'Messaging', searchIntent: 'portal first communication service providers', promise: 'make the portal useful enough that clients want the official record there', platformUse: 'in-portal messages, email notices, push, WhatsApp reminders, file sharing, and service status', statPreset: 'providerOps', actions: ['Use email for required notices.', 'Use WhatsApp and SMS only for opted-in reminders.', 'Make every message link to the right portal action.', 'Keep documents, approvals, and payments inside Baise.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'provider-client-lifetime-value-retention', title: 'Client lifetime value for service providers who want stable growth', niche: 'cross-platform', category: 'Analytics', searchIntent: 'client lifetime value service providers', promise: 'understand which services create repeat trust over time', platformUse: 'revenue dashboard, recurring services, add-ons, referrals, reviews, and campaign attribution', statPreset: 'growth', actions: ['Track first purchase and repeat purchase separately.', 'Compare one-off jobs to recurring relationships.', 'Use surveys to understand future needs.', 'Invest more in campaigns that produce loyal clients.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'provider-first-90-days-growth-plan', title: 'The first 90 days: a Baise growth plan for new service providers', niche: 'cross-platform', category: 'Growth', searchIntent: 'new service provider growth plan', promise: 'build trust assets, campaigns, and operating habits in the right order', platformUse: 'profile setup, verification, offers, CRM, quotes, payments, reviews, and analytics', statPreset: 'growth', actions: ['Days 1-15: complete profile and verification.', 'Days 16-30: publish services and first campaign.', 'Days 31-60: systemize quotes, invoices, and follow-ups.', 'Days 61-90: review analytics and improve offers.'], sourceKeys: ['sebraePaidAds', 'brazilReviews2025'] },
];

const clientTopics: Omit<BlogTopicSeed, 'audience'>[] = [
  { slug: 'client-vet-service-provider-before-booking', title: 'How to vet a service provider before you book', niche: 'cross-platform', category: 'Vetting', searchIntent: 'how to vet service provider Brazil', promise: 'choose help with confidence instead of guessing from a chat thread', platformUse: 'verified profiles, reviews, photos, quotes, secure payments, and transaction history', statPreset: 'reviews', actions: ['Check identity, ratings, and recent work.', 'Ask for a clear scope before paying.', 'Keep messages and files inside the portal.', 'Save the receipt and service history.'], sourceKeys: ['brazilReviews2025', 'brightLocalReviews2025'] },
  { slug: 'client-find-good-doctor-brazil', title: 'How to find a good doctor in Brazil without feeling overwhelmed', niche: 'medical', category: 'Medical vetting', searchIntent: 'find good doctor Brazil', promise: 'compare specialty, access, documentation, and follow-up in a calmer way', platformUse: 'verified medical profiles, specialty categories, appointment records, document requests, and follow-up reminders', statPreset: 'medical', actions: ['Match the specialty to your problem.', 'Prepare symptoms, medications, and past exams.', 'Confirm language and appointment format.', 'Keep follow-up instructions in the portal.'], sourceKeys: ['medicalDemographics2025', 'ansSectorData2026'] },
  { slug: 'client-find-good-lawyer-brazil', title: 'How to find a good lawyer in Brazil for your actual problem', niche: 'legal', category: 'Legal vetting', searchIntent: 'find good lawyer Brazil', promise: 'look for the right specialty, scope, and recordkeeping', platformUse: 'legal profiles, practice areas, document vault, consultation scheduling, invoices, and secure messages', statPreset: 'legal', actions: ['Identify the legal area first.', 'Confirm registration and relevant experience.', 'Ask what the consultation includes.', 'Keep documents and next steps organized.'], sourceKeys: ['oabLawyerRegistry', 'cnjJusticeNumbers2025'] },
  { slug: 'client-read-reviews-without-getting-misled', title: 'How to read reviews without getting misled', niche: 'cross-platform', category: 'Reviews', searchIntent: 'how to read online reviews service providers', promise: 'use reviews as evidence, not emotion', platformUse: 'verified reviews, service history, provider responses, and testimonial context', statPreset: 'reviews', actions: ['Look for patterns across recent reviews.', 'Read both positive and negative details.', 'Notice whether the provider responds professionally.', 'Combine reviews with quote clarity and proof.'], sourceKeys: ['brazilReviews2025', 'brightLocalReviews2025'] },
  { slug: 'client-verified-badges-background-checks', title: 'What verified badges and background checks should mean to clients', niche: 'cross-platform', category: 'Trust', searchIntent: 'verified provider badge background check meaning', promise: 'understand trust signals without assuming they replace judgment', platformUse: 'verified badges, provider status, ratings, completed work, and service documentation', statPreset: 'reviews', actions: ['Use verification as a starting point.', 'Still review scope, price, timing, and proof.', 'Ask questions inside the portal.', 'Avoid off-platform payment pressure.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-secure-payments-service-platform', title: 'Why secure payments matter when hiring service providers', niche: 'cross-platform', category: 'Payments', searchIntent: 'secure payments service providers Brazil', promise: 'protect your payment, receipt, and next step', platformUse: 'secure checkout, POS options, invoices, receipts, refund review, service credits, and transaction history', statPreset: 'payments', actions: ['Pay through approved platform methods.', 'Review invoice details before paying.', 'Keep receipts attached to the service.', 'Use refund or credit workflows when something changes.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-receipts-invoices-tax-records', title: 'How receipts and invoices protect your memory, proof, and taxes', niche: 'cross-platform', category: 'Records', searchIntent: 'service receipts invoices tax records client', promise: 'make every service easy to prove later', platformUse: 'transaction history, invoice IDs, client IDs, monthly downloads, annual records, and custom filters', statPreset: 'payments', actions: ['Download receipts after important services.', 'Use filters by provider, date, and service type.', 'Keep tax-relevant invoices separate.', 'Ask for corrections while details are fresh.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-quote-estimate-before-service', title: 'What a good quote or estimate should include before service starts', niche: 'cross-platform', category: 'Quotes', searchIntent: 'what should service estimate include', promise: 'avoid vague commitments by getting scope in writing', platformUse: 'quote line items, photos, service descriptions, timelines, approvals, and payment milestones', statPreset: 'payments', actions: ['Look for scope, exclusions, and assumptions.', 'Ask what happens if the job changes.', 'Confirm dates and payment timing.', 'Approve only after the details match your understanding.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-baise-vs-youtube-referrals-diy-google', title: 'Baise vs YouTube, referrals, DIY projects, and Google searches', niche: 'cross-platform', category: 'Decision help', searchIntent: 'marketplace vs referrals Google DIY service providers', promise: 'know when information is enough and when you need a trusted pro', platformUse: 'verified providers, reviews, secure transactions, background checks, records, and support workflows', statPreset: 'digital', actions: ['Use YouTube to learn vocabulary, not to replace expertise.', 'Use referrals as leads, not final proof.', 'Use Google to compare, then verify.', 'Use Baise when payment, records, and accountability matter.'], sourceKeys: ['datareportalBrazil2026', 'brazilReviews2025'] },
  { slug: 'client-avoid-diy-project-mistakes', title: 'When a DIY project should become a professional service request', niche: 'casa', category: 'Casa help', searchIntent: 'when to hire professional instead of DIY', promise: 'save money by knowing when not to improvise', platformUse: 'job posts, quotes, inspections, photo uploads, and milestone approvals', statPreset: 'reviews', actions: ['DIY only when the risk is low and reversible.', 'Hire help for safety, structure, electrical, legal, or medical issues.', 'Use photos to explain the problem.', 'Get a quote before buying materials.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-whatsapp-only-service-risk', title: 'Why a WhatsApp-only service relationship can become hard to prove', niche: 'cross-platform', category: 'Records', searchIntent: 'WhatsApp service provider risks records', promise: 'keep the convenience while protecting the record', platformUse: 'portal messages, official quotes, invoices, receipts, photos, signatures, and service history', statPreset: 'providerOps', actions: ['Use WhatsApp for quick reminders only.', 'Keep official approvals in the portal.', 'Attach photos and files to the job.', 'Do not rely on disappearing or scattered messages for proof.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-international-help-in-brazil', title: 'Finding trusted help in Brazil as an international client', niche: 'cross-platform', category: 'International clients', searchIntent: 'find trusted help Brazil international client', promise: 'reduce language, document, and payment confusion', platformUse: 'multilingual profiles, secure payments, translated service details, document vault, and support history', statPreset: 'digital', actions: ['Confirm language before booking.', 'Ask for local-process explanations.', 'Keep currency and payment details written.', 'Store documents in one portal.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'client-prepare-for-medical-appointment', title: 'How to prepare for a medical appointment so the visit is more useful', niche: 'medical', category: 'Medical help', searchIntent: 'prepare for doctor appointment Brazil', promise: 'arrive with the facts your doctor needs', platformUse: 'appointment notes, document uploads, medication lists, follow-up reminders, and service history', statPreset: 'medical', actions: ['Write your symptoms and timeline.', 'Upload recent exams when appropriate.', 'List medications and allergies.', 'Save follow-up instructions after the visit.'], sourceKeys: ['medicalDemographics2025'] },
  { slug: 'client-second-opinion-medical', title: 'When to ask for a second medical opinion', niche: 'medical', category: 'Medical help', searchIntent: 'when to get second opinion doctor', promise: 'seek clarity without panic or disrespect', platformUse: 'provider search, specialty matching, document vault, appointment history, and follow-up notes', statPreset: 'medical', actions: ['Ask when diagnosis, treatment, or surgery is unclear.', 'Bring the same documents to the second doctor.', 'Compare explanations, not personalities.', 'Keep both opinions in your records.'], sourceKeys: ['medicalDemographics2025', 'ansSectorData2026'] },
  { slug: 'client-prepare-for-legal-consultation', title: 'How to prepare for a legal consultation in Brazil', niche: 'legal', category: 'Legal help', searchIntent: 'prepare for legal consultation Brazil', promise: 'make the first meeting clearer and more efficient', platformUse: 'document vault, timeline notes, consultation booking, secure messages, and invoices', statPreset: 'legal', actions: ['Write the timeline in date order.', 'Upload contracts, messages, IDs, and notices.', 'List the outcome you want.', 'Ask what the next paid step includes.'], sourceKeys: ['oabLawyerRegistry', 'cnjJusticeNumbers2025'] },
  { slug: 'client-real-estate-legal-help', title: 'When real estate needs legal help before money moves', niche: 'legal', category: 'Real estate', searchIntent: 'real estate lawyer Brazil when needed', promise: 'protect ownership, documents, and payments before emotions take over', platformUse: 'legal profiles, title search, escrow support, quote records, and document vault', statPreset: 'legal', actions: ['Verify the property record.', 'Confirm who can sign.', 'Review debts, taxes, and possession.', 'Keep payment timing tied to written conditions.'], sourceKeys: ['oabLawyerRegistry'] },
  { slug: 'client-family-law-help', title: 'Choosing family law help with dignity and documentation', niche: 'legal', category: 'Family law', searchIntent: 'family lawyer Brazil how to choose', promise: 'handle sensitive issues with structure instead of chaos', platformUse: 'private messages, document vault, consultation scheduling, invoices, and secure records', statPreset: 'legal', actions: ['Choose a provider who explains process calmly.', 'Keep sensitive documents organized.', 'Ask about privacy and communication expectations.', 'Avoid making decisions only through emotional urgency.'], sourceKeys: ['oabLawyerRegistry'] },
  { slug: 'client-business-law-help', title: 'When your small business should talk to a lawyer before signing', niche: 'legal', category: 'Business law', searchIntent: 'small business lawyer contract review Brazil', promise: 'protect future options before obligations are locked in', platformUse: 'contract review, consultation notes, document vault, invoices, and reminders', statPreset: 'legal', actions: ['Review contracts before signature.', 'Clarify penalties, payment terms, and exit rights.', 'Keep signed versions in one place.', 'Revisit documents when the business changes.'], sourceKeys: ['oabLawyerRegistry', 'sebraePaidAds'] },
  { slug: 'client-labor-employment-help', title: 'When labor and employment questions need professional support', niche: 'legal', category: 'Labor law', searchIntent: 'labor employment lawyer Brazil help', promise: 'understand rights, documents, and next steps before acting', platformUse: 'legal profiles, secure messages, document upload, consultation booking, and service history', statPreset: 'legal', actions: ['Gather contracts, pay records, and messages.', 'Avoid public posts before getting guidance.', 'Ask what documents matter most.', 'Keep every step organized.'], sourceKeys: ['cnjJusticeNumbers2025'] },
  { slug: 'client-consumer-protection-help', title: 'Consumer protection: what to document before asking for help', niche: 'legal', category: 'Consumer law', searchIntent: 'consumer protection Brazil document complaint', promise: 'make your complaint easier to evaluate', platformUse: 'photo uploads, receipts, provider messages, document vault, and consultation notes', statPreset: 'reviews', actions: ['Save receipts, photos, screenshots, and dates.', 'Write the issue in plain language.', 'Document attempts to resolve it.', 'Ask a qualified provider what next step fits.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-notary-apostille-documents', title: 'Notary, apostille, and document authentication: what clients should know', niche: 'legal', category: 'Notary services', searchIntent: 'notary apostille Brazil documents', promise: 'avoid delays by matching the document to the right process', platformUse: 'notary service categories, document upload, quote requests, appointment scheduling, and receipts', statPreset: 'legal', actions: ['Confirm the destination country or authority.', 'Ask whether translation is needed.', 'Keep copies of every submitted document.', 'Track the service status in the portal.'], sourceKeys: ['oabLawyerRegistry'] },
  { slug: 'client-escrow-title-search-basics', title: 'Escrow and title search basics for safer property decisions', niche: 'legal', category: 'Real estate', searchIntent: 'escrow title search Brazil basics', promise: 'understand why records and payment timing matter', platformUse: 'title search category, escrow support, document vault, milestone payments, and transaction history', statPreset: 'payments', actions: ['Do not move money before key records are reviewed.', 'Use milestone logic for complex transactions.', 'Keep title documents and receipts together.', 'Ask what conditions unlock payment.'], sourceKeys: ['oabLawyerRegistry'] },
  { slug: 'client-medical-expert-witnesses', title: 'What medical expert witnesses do and when they may be needed', niche: 'medical', category: 'Medical legal', searchIntent: 'medical expert witness Brazil', promise: 'understand the role without confusing it with treatment', platformUse: 'medical expert categories, legal support links, document vault, appointment notes, and invoices', statPreset: 'medical', actions: ['Clarify whether you need care, review, or expert opinion.', 'Collect medical records in order.', 'Ask about scope and limitations.', 'Keep reports attached to the right matter.'], sourceKeys: ['medicalDemographics2025', 'oabLawyerRegistry'] },
  { slug: 'client-hiring-cleaning-services', title: 'How to hire cleaning services with clear expectations', niche: 'casa', category: 'Home services', searchIntent: 'hire cleaning service Brazil checklist', promise: 'make recurring or one-time cleaning smoother', platformUse: 'service listings, recurring bookings, checklists, payments, and reviews', statPreset: 'reviews', actions: ['Define rooms, tasks, timing, and supplies.', 'Choose one-off or recurring service.', 'Document access instructions privately.', 'Review the service after completion.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-renovation-project-hiring', title: 'How to hire for a renovation project without losing control of scope', niche: 'casa', category: 'Home services', searchIntent: 'hire renovation provider Brazil', promise: 'use milestones, photos, and approvals to stay organized', platformUse: 'quotes, milestone payments, photo proof, subcontractor notes, inspections, and signatures', statPreset: 'payments', actions: ['Start with inspection and scope.', 'Approve milestones before work begins.', 'Use photos for proof and changes.', 'Keep every payment tied to a phase.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-inspections-before-payment', title: 'Why inspections should happen before final payment', niche: 'casa', category: 'Home services', searchIntent: 'inspection before final payment service work', promise: 'confirm quality before closing the record', platformUse: 'inspection notes, photos, sign-off, payment milestones, and issue tracking', statPreset: 'payments', actions: ['Inspect against the quote, not vague expectations.', 'Photograph unresolved issues.', 'Use sign-off only when the work is acceptable.', 'Keep final payment and receipt together.'], sourceKeys: ['brightLocalReviews2025'] },
  { slug: 'client-recurring-monthly-services', title: 'When monthly or weekly service plans make more sense than one-off jobs', niche: 'cross-platform', category: 'Payments', searchIntent: 'monthly weekly service plans when to use', promise: 'pay for continuity when the need repeats', platformUse: 'recurring bookings, subscription payments, reminders, invoices, and service history', statPreset: 'payments', actions: ['Use recurring service for ongoing needs.', 'Review the plan after the first month.', 'Keep cancellations and changes written.', 'Download monthly receipts.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-flexible-payment-plans', title: 'Flexible payment plans: how to break up payments safely', niche: 'cross-platform', category: 'Payments', searchIntent: 'flexible payment plans service providers', promise: 'align payment timing with delivery and trust', platformUse: 'payment plans, milestones, benchmark releases, receipts, and transaction filters', statPreset: 'payments', actions: ['Ask what each payment unlocks.', 'Keep timeline and amount in writing.', 'Avoid off-platform installment agreements.', 'Save every receipt.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-refunds-service-credits', title: 'Refunds and service credits: what clients should expect', niche: 'cross-platform', category: 'Payments', searchIntent: 'refund service credit service platform', promise: 'understand your options when service changes', platformUse: 'refund requests, service credits, internal balance, review items, and portal messages', statPreset: 'payments', actions: ['Explain the issue clearly.', 'Attach proof when possible.', 'Review whether a fix, credit, or refund fits.', 'Keep the final decision with the original invoice.'], sourceKeys: ['brightLocalReviews2025'] },
  { slug: 'client-timeline-benchmarks-service-work', title: 'Timelines and benchmarks: how to know what should happen next', niche: 'cross-platform', category: 'Projects', searchIntent: 'service project timeline benchmarks client', promise: 'turn a vague project into visible progress', platformUse: 'project stages, calendar, milestone payments, photo updates, and notifications', statPreset: 'payments', actions: ['Ask for stages before work starts.', 'Match each stage to a deliverable.', 'Use notifications to track changes.', 'Approve benchmark releases carefully.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-signoff-photo-proof', title: 'Client sign-off and photo proof: what to check before approving work', niche: 'casa', category: 'Projects', searchIntent: 'client sign off photo proof service work', promise: 'approve with confidence and preserve proof', platformUse: 'photo upload, signatures, work-completed proof, unexpected-problem notes, and quote attachments', statPreset: 'payments', actions: ['Compare photos to the agreed scope.', 'Ask questions before signing.', 'Document unresolved issues.', 'Save the signed approval.'], sourceKeys: ['brightLocalReviews2025'] },
  { slug: 'client-document-vault-benefits', title: 'Why the document vault matters even after the service is done', niche: 'cross-platform', category: 'Records', searchIntent: 'document vault service records client benefits', promise: 'keep proof, receipts, and files ready when life asks for them', platformUse: 'client vault, categories, previews, receipts, photos, signatures, and tax records', statPreset: 'payments', actions: ['Upload important files once.', 'Use categories so files are easy to find.', 'Review before tax or legal deadlines.', 'Keep sensitive documents out of public chats.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-transaction-history-downloads', title: 'How to use transaction history downloads for proof and planning', niche: 'cross-platform', category: 'Records', searchIntent: 'download transaction history invoices receipts', promise: 'turn service history into a clean record', platformUse: 'monthly, MTD, quarterly, annual, custom filters, invoice IDs, and receipt downloads', statPreset: 'payments', actions: ['Filter by provider, service, and date.', 'Download monthly records for recurring services.', 'Keep annual exports for taxes.', 'Flag missing or incorrect invoices early.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-language-barriers-service-provider', title: 'How to handle language barriers when hiring providers in Brazil', niche: 'cross-platform', category: 'International clients', searchIntent: 'language barrier hiring service provider Brazil', promise: 'make sure everyone understands scope, timing, and payment', platformUse: 'language preferences, translated descriptions, portal summaries, secure messages, and document records', statPreset: 'digital', actions: ['Choose providers who list your language.', 'Ask for written summaries.', 'Confirm technical terms before approving.', 'Keep translated documents in the vault.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'client-privacy-safety-service-platform', title: 'Privacy and safety when sharing service details online', niche: 'cross-platform', category: 'Trust', searchIntent: 'privacy safety service marketplace client', promise: 'share enough for help without exposing more than needed', platformUse: 'secure messaging, protected documents, permissioned files, verified profiles, and account access', statPreset: 'digital', actions: ['Do not post sensitive facts publicly.', 'Use portal uploads for documents.', 'Check who can view each file.', 'Remove access when a matter is complete.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'client-questions-to-ask-provider', title: 'Ten questions to ask before you hire a provider', niche: 'cross-platform', category: 'Vetting', searchIntent: 'questions to ask before hiring service provider', promise: 'move from hope to clarity before booking', platformUse: 'provider messages, quote requests, reviews, service history, payments, and approvals', statPreset: 'reviews', actions: ['Ask what is included and excluded.', 'Ask who performs the work.', 'Ask what happens if scope changes.', 'Ask how payment, proof, and follow-up work.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-red-flags-without-panic', title: 'Service-provider red flags without panic or fearmongering', niche: 'cross-platform', category: 'Vetting', searchIntent: 'service provider red flags', promise: 'notice patterns that deserve more questions', platformUse: 'verified profiles, official quotes, secure payments, reviews, and portal records', statPreset: 'reviews', actions: ['Be careful with pressure to pay off-platform.', 'Pause when scope is vague.', 'Ask for proof when claims are hard to verify.', 'Use support when something feels inconsistent.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-use-platform-messages', title: 'Why important service messages should stay inside the platform', niche: 'cross-platform', category: 'Records', searchIntent: 'why use platform messages service provider', promise: 'make decisions easier to find and prove', platformUse: 'portal messages, notifications, attachments, quote approvals, payment notes, and service records', statPreset: 'providerOps', actions: ['Use portal threads for approvals and changes.', 'Attach files to the right service.', 'Avoid mixing multiple jobs in one chat.', 'Review the thread before payment or sign-off.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-leave-helpful-review', title: 'How to leave a review that actually helps the next client', niche: 'cross-platform', category: 'Reviews', searchIntent: 'how to write helpful service review', promise: 'share useful details without oversharing private facts', platformUse: 'verified review forms, testimonial requests, approval workflow, and service history', statPreset: 'reviews', actions: ['Mention the service type and result.', 'Comment on communication and timeliness.', 'Avoid private medical or legal details.', 'Upload video testimonials only with consent.'], sourceKeys: ['googleReviewTips', 'brightLocalReviews2025'] },
  { slug: 'client-compare-medical-credentials', title: 'How to compare medical credentials without pretending to be a doctor', niche: 'medical', category: 'Medical vetting', searchIntent: 'compare doctor credentials specialty Brazil', promise: 'ask better questions and choose the right care path', platformUse: 'medical profiles, specialty labels, verified badges, reviews, and appointment notes', statPreset: 'medical', actions: ['Match specialty to your need.', 'Ask about experience with similar cases.', 'Bring records instead of relying on memory.', 'Use follow-up notes to understand the care plan.'], sourceKeys: ['medicalDemographics2025'] },
  { slug: 'client-health-plan-private-pay', title: 'Health plan vs private pay: what to clarify before booking', niche: 'medical', category: 'Medical payments', searchIntent: 'health plan private pay doctor appointment Brazil', promise: 'avoid payment surprises and appointment confusion', platformUse: 'appointment booking, payment status, receipts, plan notes, and transaction history', statPreset: 'medical', actions: ['Ask what is covered before booking.', 'Confirm whether exams or follow-ups are separate.', 'Request a receipt for every payment.', 'Keep plan and payment notes in your history.'], sourceKeys: ['ansSectorData2026'] },
  { slug: 'client-emergency-vs-scheduled-service', title: 'Emergency, urgent, or scheduled: choosing the right service path', niche: 'cross-platform', category: 'Booking', searchIntent: 'emergency urgent scheduled service booking', promise: 'match the provider search to the real level of urgency', platformUse: 'urgency levels, booking calendar, notifications, quote requests, and support routing', statPreset: 'providerOps', actions: ['Use emergency only when timing truly matters.', 'Use urgent for needs within days.', 'Use scheduled for planning and better pricing.', 'Update the provider if urgency changes.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-relocation-support-brazil', title: 'Relocating to Brazil: the service support layers to organize early', niche: 'cross-platform', category: 'International clients', searchIntent: 'relocation support services Brazil', promise: 'coordinate legal, medical, home, and document needs in one system', platformUse: 'legal support, medical support, casa services, document vault, payments, and recurring reminders', statPreset: 'digital', actions: ['List legal, medical, housing, and family needs.', 'Prioritize documents and appointments.', 'Use one portal record per service.', 'Keep receipts for relocation and tax records.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'client-home-health-caregiver-support', title: 'How to choose home health or caregiver support carefully', niche: 'medical', category: 'Medical help', searchIntent: 'choose caregiver home health support Brazil', promise: 'protect dignity, safety, schedule, and records', platformUse: 'verified profiles, recurring bookings, care notes, family access, payments, and reviews', statPreset: 'medical', actions: ['Define care tasks and schedule clearly.', 'Check experience and communication style.', 'Keep family updates in the portal.', 'Review service quality regularly.'], sourceKeys: ['medicalDemographics2025'] },
  { slug: 'client-entertainment-ip-law-help', title: 'Creators and small brands: when IP or entertainment law support matters', niche: 'legal', category: 'IP and entertainment', searchIntent: 'IP entertainment lawyer Brazil creators', promise: 'protect work before a deal, post, or partnership gets bigger', platformUse: 'legal profiles, contract review, document vault, consultation notes, and invoice records', statPreset: 'legal', actions: ['Save drafts, agreements, and campaign terms.', 'Ask about ownership and usage rights.', 'Review sponsorship or licensing terms before signing.', 'Keep final contracts organized.'], sourceKeys: ['oabLawyerRegistry', 'datareportalBrazil2026'] },
  { slug: 'client-contract-review-before-signing', title: 'Contract review: why the boring paragraph can be the expensive one', niche: 'legal', category: 'Contracts', searchIntent: 'contract review before signing Brazil', promise: 'understand obligations before they become problems', platformUse: 'contract upload, legal consultation, notes, quote approval, and document vault', statPreset: 'legal', actions: ['Upload the full contract, not screenshots only.', 'Ask about payment, cancellation, penalties, and jurisdiction.', 'Get changes in writing.', 'Store the signed version.'], sourceKeys: ['oabLawyerRegistry'] },
  { slug: 'client-environmental-admin-law-help', title: 'When administrative or environmental questions need specialized help', niche: 'legal', category: 'Specialty legal', searchIntent: 'administrative environmental lawyer Brazil', promise: 'find the right specialty instead of forcing a general answer', platformUse: 'practice-area filters, consultation booking, document vault, timelines, and secure messages', statPreset: 'legal', actions: ['Identify the government body or regulation involved.', 'Collect notices, permits, and deadlines.', 'Ask about specialty experience.', 'Track every deadline in the portal.'], sourceKeys: ['cnjJusticeNumbers2025'] },
  { slug: 'client-social-proof-badges', title: 'How to use badges, ratings, and social proof without outsourcing your judgment', niche: 'cross-platform', category: 'Trust', searchIntent: 'badges ratings social proof service provider', promise: 'combine trust signals with practical questions', platformUse: 'verified badges, ratings, reviews, work samples, response history, and secure payments', statPreset: 'reviews', actions: ['Use badges to narrow choices.', 'Use reviews to understand experience.', 'Use quotes to confirm fit.', 'Use records to protect the relationship.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-ai-search-vs-trusted-provider', title: 'AI search can explain options, but it cannot verify your provider', niche: 'cross-platform', category: 'Decision help', searchIntent: 'AI search vs verified service provider', promise: 'use AI for education while using Baise for trust and records', platformUse: 'verified provider marketplace, reviews, background checks, quotes, payments, and service history', statPreset: 'digital', actions: ['Use AI to learn terms and questions.', 'Do not use AI as proof of credentials.', 'Confirm providers inside the platform.', 'Keep final decisions attached to real records.'], sourceKeys: ['datareportalBrazil2026'] },
  { slug: 'client-premium-support-when-worth-it', title: 'When premium support is worth it for clients and service seekers', niche: 'cross-platform', category: 'Premium support', searchIntent: 'premium service platform support worth it', promise: 'know when extra support saves time, confusion, or risk', platformUse: 'premium features, priority support, transaction history, document vault, reminders, and concierge guidance', statPreset: 'payments', actions: ['Use premium when records, timing, or coordination matter.', 'Compare the cost to the cost of confusion.', 'Use support before the deadline, not after.', 'Review all premium benefits inside your account.'], sourceKeys: ['brazilReviews2025'] },
  { slug: 'client-value-based-add-ons', title: 'How to decide whether an add-on service actually adds value', niche: 'cross-platform', category: 'Premium support', searchIntent: 'service add ons worth it client', promise: 'choose recommended services because they fit your life or business, not because they were pushed', platformUse: 'recommended products, value explanations, quote requests, client surveys, and transaction history', statPreset: 'growth', actions: ['Ask what problem the add-on solves.', 'Compare timing, cost, and risk avoided.', 'Request a quote before approving.', 'Mark not now if the value is real but timing is wrong.'], sourceKeys: ['sebraePaidAds'] },
  { slug: 'client-intake-surveys-better-recommendations', title: 'Why answering intake surveys can make recommendations more useful', niche: 'cross-platform', category: 'Client intelligence', searchIntent: 'client intake survey service recommendations', promise: 'help the platform understand your occupation, lifestyle, family, goals, and service needs over time', platformUse: 'client insight surveys, demographics, product-fit scoring, reminders, and value-based campaigns', statPreset: 'growth', actions: ['Answer only what helps improve service.', 'Update your profile when life or business changes.', 'Use recommendations as prompts, not pressure.', 'Ask for a human follow-up when a recommendation feels important.'], sourceKeys: ['sebraePaidAds', 'sebraeWhatsappServices'] },
  { slug: 'client-family-service-records', title: 'Why families should keep service records together', niche: 'cross-platform', category: 'Records', searchIntent: 'family service records receipts documents', promise: 'make household, legal, medical, and home history easier to manage', platformUse: 'family records, document vault, receipts, recurring services, permissions, and calendar reminders', statPreset: 'payments', actions: ['Keep one record per service.', 'Share access only with the right people.', 'Save receipts and sign-offs.', 'Review history before booking repeat work.'], sourceKeys: ['sebraeWhatsappServices'] },
  { slug: 'client-annual-service-review', title: 'The annual service review every client should do', niche: 'cross-platform', category: 'Planning', searchIntent: 'annual service review home medical legal records', promise: 'turn your service history into smarter planning', platformUse: 'annual transaction downloads, provider history, reviews, documents, reminders, and recommended add-ons', statPreset: 'payments', actions: ['Download annual records.', 'List recurring needs for the next year.', 'Review providers you would hire again.', 'Ask what preventive service would save future stress.'], sourceKeys: ['sebraeWhatsappServices'] },
];

const sourceKeysFor = (topic: BlogTopicSeed) => {
  const defaults: Record<BlogStatPreset, string[]> = {
    digital: ['datareportalBrazil2026'],
    providerOps: ['sebraeWhatsappServices'],
    reviews: ['brazilReviews2025', 'brightLocalReviews2025', 'googleReviewTips'],
    medical: ['medicalDemographics2025', 'ansSectorData2026'],
    legal: ['oabLawyerRegistry', 'cnjJusticeNumbers2025'],
    payments: ['sebraeWhatsappServices'],
    growth: ['sebraePaidAds', 'datareportalBrazil2026'],
  };
  return Array.from(new Set([...(topic.sourceKeys || []), ...defaults[topic.statPreset]])).map((key) => BLOG_SOURCES[key]).filter(Boolean);
};

const audienceCta = (topic: BlogTopicSeed) => {
  if (topic.audience === 'provider') {
    return {
      ctaTitle: 'Build the workflow in your provider dashboard.',
      ctaText:
        'Use Baise to turn this lesson into action: update your services, launch the right campaign, collect payment cleanly, and keep every client record in one place.',
    };
  }
  return {
    ctaTitle: 'Find trusted help with the record protected.',
    ctaText:
      'Use Baise to compare trusted providers, request a clear quote, keep messages and documents together, and preserve receipts, invoices, reviews, and service history.',
  };
};

const buildDeck = (topic: BlogTopicSeed) =>
  topic.audience === 'provider'
    ? `${topic.promise}. This guide teaches providers how to use Baise for ${topic.platformUse}.`
    : `${topic.promise}. This guide teaches clients how to use Baise for ${topic.platformUse}.`;

const buildStory = (topic: BlogTopicSeed) =>
  topic.audience === 'provider'
    ? `A serious client usually decides before they ever speak to you. They compare your profile, your proof, your response quality, your quote, and whether the next step feels organized. The providers who win are not always the loudest. They are the ones who make trust easier to see and easier to act on.`
    : `Most people do not want a complicated search. They want a provider who is competent, clear, safe, responsive, and easy to prove later if a document, receipt, or follow-up matters. The goal is not to become an expert in every field. The goal is to know what to verify before choosing.`;

const buildLesson = (topic: BlogTopicSeed) =>
  topic.audience === 'provider'
    ? `The lesson: ${topic.promise}. A better service business is not built from one more random tool. It is built by connecting profile trust, client intake, quotes, payments, documents, communication, reviews, and follow-up into one operating rhythm.`
    : `The lesson: ${topic.promise}. Good help is easier to find when the decision is documented: who is doing the work, what is included, what it costs, what proof exists, and what happens next.`;

const buildStrategy = (topic: BlogTopicSeed) =>
  topic.audience === 'provider'
    ? `Use the platform intentionally for ${topic.platformUse}. Treat every profile update, quote, message, invoice, photo, and review as part of the same growth system.`
    : `Use the platform intentionally for ${topic.platformUse}. Treat every profile, review, quote, invoice, photo, signature, and message as part of one clean decision record.`;

const buildBlogPost = (topic: BlogTopicSeed, number: number): BaiseBlogPost => {
  const chart = CHART_PRESETS[topic.statPreset];
  const cta = audienceCta(topic);
  return {
    ...topic,
    id: `${topic.audience}-${topic.slug}`,
    number,
    readTime: '5 min read',
    deck: buildDeck(topic),
    story: buildStory(topic),
    lesson: buildLesson(topic),
    strategy: buildStrategy(topic),
    dataNarrative: chart.narrative,
    chartTitle: chart.title,
    chartData: chart.data,
    sources: sourceKeysFor(topic),
    ctaTitle: cta.ctaTitle,
    ctaText: cta.ctaText,
  };
};

export const PROVIDER_BLOG_POSTS = providerTopics.map((topic, index) =>
  buildBlogPost({ ...topic, audience: 'provider' }, index + 1),
);

export const CLIENT_BLOG_POSTS = clientTopics.map((topic, index) =>
  buildBlogPost({ ...topic, audience: 'client' }, index + 1),
);

export const BAISE_BLOG_POSTS = [...PROVIDER_BLOG_POSTS, ...CLIENT_BLOG_POSTS];

export const getBlogPostBySlug = (slug?: string) => BAISE_BLOG_POSTS.find((post) => post.slug === slug);

export const getRelatedBlogPosts = (post: BaiseBlogPost, count = 3) =>
  BAISE_BLOG_POSTS.filter((candidate) => candidate.slug !== post.slug && (candidate.audience === post.audience || candidate.niche === post.niche))
    .slice(0, count);
